<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>7&nbsp; Session 5 — Regression – Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../demos/session-05b-classification.html" rel="next">
<link href="../demos/session-04-intro-ml-ai.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-7202036dd3638cbfcbeb4151d116aa42.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../demos/session-01-python-refresher.html">Workshop</a></li><li class="breadcrumb-item"><a href="../demos/session-05-regression.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Session 5 — Regression</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Science</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../setup-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Environment Setup Guide</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Workshop</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/session-01-python-refresher.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Session 1 — Python Refresher</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/session-02-numpy-pandas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Session 2 — Introduction to Python Libraries: NumPy &amp; Pandas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/session-03-eda-preprocessing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Session 3 — EDA &amp; Data Preprocessing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/session-04-intro-ml-ai.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Session 4 — Introduction to Artificial Intelligence &amp; Machine Learning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/session-05-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Session 5 — Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/session-05b-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Session 5B — Classification &amp; Deployment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/session-05c-deployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Session 5C — Model Deployment &amp; Streamlit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/session-06-big-data-part1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Part 1 — Python MapReduce Without Hadoop</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../demos/session-07-big-data-part2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">error: true</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part A — Getting hold of data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-01-introduction-to-data-science.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Session 1 — Introduction to Data Science</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-02-data-collection-and-pre-processing-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Session 2 — Data Collection and Pre-Processing Overview</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part B — Making data fit to use</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-03-data-cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Session 3 — Data Cleaning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-04-data-integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Session 4 — Data Integration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-05-data-transformation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Session 5 — Data Transformation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-06-data-reduction-and-discretization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Session 6 — Data Reduction and Discretization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part C — Understanding data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-07-descriptive-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Session 7 — Descriptive Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-08-exploratory-data-analytics-eda-and-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Session 8 — Exploratory Data Analysis and Visualization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Part D — Learning from data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-09-supervised-learning-techniques.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Session 9 — Supervised Learning Techniques</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-10-unsupervised-learning-techniques-clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Session 10 — Unsupervised Learning and Clustering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-11-data-model-evaluation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Session 11 — Model Evaluation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-12-model-saving-and-deployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Session 12 — Model Saving and Deployment</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Part E — Data at scale</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-13-big-data-analytics-fundamentals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Session 13 — Big Data Analytics Fundamentals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-14-distributed-data-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Session 14 — Distributed Data Processing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-15-nosql-databases-and-scaled-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Session 15 — NoSQL Databases and Visualization at Scale</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../sessions/session-16-open-ended-module-implementation-and-capstone.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Session 16 — Capstone: The End-to-End Project</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes"><span class="header-section-number">7.1</span> 🎯 Learning outcomes</a></li>
  <li><a href="#how-this-session-is-organised" id="toc-how-this-session-is-organised" class="nav-link" data-scroll-target="#how-this-session-is-organised"><span class="header-section-number">7.2</span> How this session is organised</a></li>
  <li><a href="#supervised-learning-regression-and-classification" id="toc-supervised-learning-regression-and-classification" class="nav-link" data-scroll-target="#supervised-learning-regression-and-classification"><span class="header-section-number">8</span> Supervised learning: regression and classification</a>
  <ul class="collapse">
  <li><a href="#the-two-kinds" id="toc-the-two-kinds" class="nav-link" data-scroll-target="#the-two-kinds"><span class="header-section-number">8.1</span> The two kinds</a></li>
  <li><a href="#the-trap-numbers-that-are-really-categories" id="toc-the-trap-numbers-that-are-really-categories" class="nav-link" data-scroll-target="#the-trap-numbers-that-are-really-categories"><span class="header-section-number">8.2</span> The trap: numbers that are really categories</a></li>
  <li><a href="#practice" id="toc-practice" class="nav-link" data-scroll-target="#practice"><span class="header-section-number">8.3</span> ✏️ Practice</a></li>
  </ul></li>
  <li><a href="#use-case-1-salary-from-experience" id="toc-use-case-1-salary-from-experience" class="nav-link" data-scroll-target="#use-case-1-salary-from-experience"><span class="header-section-number">9</span> Use case 1 — Salary from experience</a>
  <ul class="collapse">
  <li><a href="#step-1-import-the-libraries-and-load-the-data" id="toc-step-1-import-the-libraries-and-load-the-data" class="nav-link" data-scroll-target="#step-1-import-the-libraries-and-load-the-data"><span class="header-section-number">9.1</span> Step 1 — Import the libraries and load the data</a></li>
  <li><a href="#step-2-exploratory-data-analysis" id="toc-step-2-exploratory-data-analysis" class="nav-link" data-scroll-target="#step-2-exploratory-data-analysis"><span class="header-section-number">9.2</span> Step 2 — Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#correlation-does-experience-actually-relate-to-salary" id="toc-correlation-does-experience-actually-relate-to-salary" class="nav-link" data-scroll-target="#correlation-does-experience-actually-relate-to-salary"><span class="header-section-number">9.2.1</span> Correlation — does experience actually relate to salary?</a></li>
  </ul></li>
  <li><a href="#step-3-preprocessing" id="toc-step-3-preprocessing" class="nav-link" data-scroll-target="#step-3-preprocessing"><span class="header-section-number">9.3</span> Step 3 — Preprocessing</a>
  <ul class="collapse">
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values"><span class="header-section-number">9.3.1</span> Missing values</a></li>
  <li><a href="#duplicates" id="toc-duplicates" class="nav-link" data-scroll-target="#duplicates"><span class="header-section-number">9.3.2</span> Duplicates</a></li>
  <li><a href="#outliers" id="toc-outliers" class="nav-link" data-scroll-target="#outliers"><span class="header-section-number">9.3.3</span> Outliers</a></li>
  <li><a href="#encoding-and-scaling" id="toc-encoding-and-scaling" class="nav-link" data-scroll-target="#encoding-and-scaling"><span class="header-section-number">9.3.4</span> Encoding and scaling</a></li>
  </ul></li>
  <li><a href="#step-4-train-test-split" id="toc-step-4-train-test-split" class="nav-link" data-scroll-target="#step-4-train-test-split"><span class="header-section-number">9.4</span> Step 4 — Train-test split</a></li>
  <li><a href="#step-5-model-selection-and-training" id="toc-step-5-model-selection-and-training" class="nav-link" data-scroll-target="#step-5-model-selection-and-training"><span class="header-section-number">9.5</span> Step 5 — Model selection and training</a></li>
  <li><a href="#step-6-making-predictions" id="toc-step-6-making-predictions" class="nav-link" data-scroll-target="#step-6-making-predictions"><span class="header-section-number">9.6</span> Step 6 — Making predictions</a></li>
  <li><a href="#step-7-evaluation-metrics-properly" id="toc-step-7-evaluation-metrics-properly" class="nav-link" data-scroll-target="#step-7-evaluation-metrics-properly"><span class="header-section-number">9.7</span> Step 7 — Evaluation metrics, properly</a>
  <ul class="collapse">
  <li><a href="#the-problem-with-just-adding-up-the-errors" id="toc-the-problem-with-just-adding-up-the-errors" class="nav-link" data-scroll-target="#the-problem-with-just-adding-up-the-errors"><span class="header-section-number">9.7.1</span> The problem with just adding up the errors</a></li>
  <li><a href="#mae-mean-absolute-error" id="toc-mae-mean-absolute-error" class="nav-link" data-scroll-target="#mae-mean-absolute-error"><span class="header-section-number">9.7.2</span> MAE — Mean Absolute Error</a></li>
  <li><a href="#mse-mean-squared-error" id="toc-mse-mean-squared-error" class="nav-link" data-scroll-target="#mse-mean-squared-error"><span class="header-section-number">9.7.3</span> MSE — Mean Squared Error</a></li>
  <li><a href="#rmse-root-mean-squared-error" id="toc-rmse-root-mean-squared-error" class="nav-link" data-scroll-target="#rmse-root-mean-squared-error"><span class="header-section-number">9.7.4</span> RMSE — Root Mean Squared Error</a></li>
  <li><a href="#mae-and-rmse-together-tell-you-something-neither-says-alone" id="toc-mae-and-rmse-together-tell-you-something-neither-says-alone" class="nav-link" data-scroll-target="#mae-and-rmse-together-tell-you-something-neither-says-alone"><span class="header-section-number">9.7.5</span> MAE and RMSE together tell you something neither says alone</a></li>
  <li><a href="#r²-the-coefficient-of-determination" id="toc-r²-the-coefficient-of-determination" class="nav-link" data-scroll-target="#r²-the-coefficient-of-determination"><span class="header-section-number">9.7.6</span> R² — the coefficient of determination</a></li>
  <li><a href="#the-four-metrics-side-by-side" id="toc-the-four-metrics-side-by-side" class="nav-link" data-scroll-target="#the-four-metrics-side-by-side"><span class="header-section-number">9.7.7</span> The four metrics side by side</a></li>
  </ul></li>
  <li><a href="#step-8-reading-the-model" id="toc-step-8-reading-the-model" class="nav-link" data-scroll-target="#step-8-reading-the-model"><span class="header-section-number">9.8</span> Step 8 — Reading the model</a></li>
  <li><a href="#step-9-plotting-the-result" id="toc-step-9-plotting-the-result" class="nav-link" data-scroll-target="#step-9-plotting-the-result"><span class="header-section-number">9.9</span> Step 9 — Plotting the result</a>
  <ul class="collapse">
  <li><a href="#two-diagnostic-plots-worth-drawing-every-time" id="toc-two-diagnostic-plots-worth-drawing-every-time" class="nav-link" data-scroll-target="#two-diagnostic-plots-worth-drawing-every-time"><span class="header-section-number">9.9.1</span> Two diagnostic plots worth drawing every time</a></li>
  </ul></li>
  <li><a href="#practice-use-case-1" id="toc-practice-use-case-1" class="nav-link" data-scroll-target="#practice-use-case-1"><span class="header-section-number">9.10</span> ✏️ Practice — use case 1</a></li>
  </ul></li>
  <li><a href="#use-case-2-advertising-spend-and-sales" id="toc-use-case-2-advertising-spend-and-sales" class="nav-link" data-scroll-target="#use-case-2-advertising-spend-and-sales"><span class="header-section-number">10</span> Use case 2 — Advertising spend and sales</a>
  <ul class="collapse">
  <li><a href="#steps-12-load-and-explore" id="toc-steps-12-load-and-explore" class="nav-link" data-scroll-target="#steps-12-load-and-explore"><span class="header-section-number">10.1</span> Steps 1–2 — Load and explore</a>
  <ul class="collapse">
  <li><a href="#correlation-now-genuinely-useful" id="toc-correlation-now-genuinely-useful" class="nav-link" data-scroll-target="#correlation-now-genuinely-useful"><span class="header-section-number">10.1.1</span> Correlation — now genuinely useful</a></li>
  <li><a href="#seeing-the-three-relationships" id="toc-seeing-the-three-relationships" class="nav-link" data-scroll-target="#seeing-the-three-relationships"><span class="header-section-number">10.1.2</span> Seeing the three relationships</a></li>
  </ul></li>
  <li><a href="#steps-35-split-train-predict" id="toc-steps-35-split-train-predict" class="nav-link" data-scroll-target="#steps-35-split-train-predict"><span class="header-section-number">10.2</span> Steps 3–5 — Split, train, predict</a></li>
  <li><a href="#step-6-evaluate" id="toc-step-6-evaluate" class="nav-link" data-scroll-target="#step-6-evaluate"><span class="header-section-number">10.3</span> Step 6 — Evaluate</a></li>
  <li><a href="#step-7-reading-three-coefficients" id="toc-step-7-reading-three-coefficients" class="nav-link" data-scroll-target="#step-7-reading-three-coefficients"><span class="header-section-number">10.4</span> Step 7 — Reading three coefficients</a>
  <ul class="collapse">
  <li><a href="#the-correlation-and-the-coefficient-disagree-and-both-are-right" id="toc-the-correlation-and-the-coefficient-disagree-and-both-are-right" class="nav-link" data-scroll-target="#the-correlation-and-the-coefficient-disagree-and-both-are-right"><span class="header-section-number">10.4.1</span> ⚠️ The correlation and the coefficient disagree — and both are right</a></li>
  </ul></li>
  <li><a href="#step-8-should-we-drop-newspaper" id="toc-step-8-should-we-drop-newspaper" class="nav-link" data-scroll-target="#step-8-should-we-drop-newspaper"><span class="header-section-number">10.5</span> Step 8 — Should we drop Newspaper?</a></li>
  <li><a href="#practice-use-case-2" id="toc-practice-use-case-2" class="nav-link" data-scroll-target="#practice-use-case-2"><span class="header-section-number">10.6</span> ✏️ Practice — use case 2</a></li>
  </ul></li>
  <li><a href="#use-case-3-used-car-prices" id="toc-use-case-3-used-car-prices" class="nav-link" data-scroll-target="#use-case-3-used-car-prices"><span class="header-section-number">11</span> Use case 3 — Used car prices</a>
  <ul class="collapse">
  <li><a href="#step-1-load-and-explore" id="toc-step-1-load-and-explore" class="nav-link" data-scroll-target="#step-1-load-and-explore"><span class="header-section-number">11.1</span> Step 1 — Load and explore</a>
  <ul class="collapse">
  <li><a href="#looking-at-the-text-columns" id="toc-looking-at-the-text-columns" class="nav-link" data-scroll-target="#looking-at-the-text-columns"><span class="header-section-number">11.1.1</span> Looking at the text columns</a></li>
  </ul></li>
  <li><a href="#step-2-preprocessing" id="toc-step-2-preprocessing" class="nav-link" data-scroll-target="#step-2-preprocessing"><span class="header-section-number">11.2</span> Step 2 — Preprocessing</a>
  <ul class="collapse">
  <li><a href="#dropping-columns-that-cannot-help" id="toc-dropping-columns-that-cannot-help" class="nav-link" data-scroll-target="#dropping-columns-that-cannot-help"><span class="header-section-number">11.2.1</span> Dropping columns that cannot help</a></li>
  <li><a href="#encoding" id="toc-encoding" class="nav-link" data-scroll-target="#encoding"><span class="header-section-number">11.2.2</span> Encoding</a></li>
  </ul></li>
  <li><a href="#step-3-split-and-scale" id="toc-step-3-split-and-scale" class="nav-link" data-scroll-target="#step-3-split-and-scale"><span class="header-section-number">11.3</span> Step 3 — Split and scale</a>
  <ul class="collapse">
  <li><a href="#does-scaling-actually-change-anything-here" id="toc-does-scaling-actually-change-anything-here" class="nav-link" data-scroll-target="#does-scaling-actually-change-anything-here"><span class="header-section-number">11.3.1</span> ⚠️ Does scaling actually change anything here?</a></li>
  </ul></li>
  <li><a href="#step-4-train-and-evaluate" id="toc-step-4-train-and-evaluate" class="nav-link" data-scroll-target="#step-4-train-and-evaluate"><span class="header-section-number">11.4</span> Step 4 — Train and evaluate</a>
  <ul class="collapse">
  <li><a href="#read-this-honestly" id="toc-read-this-honestly" class="nav-link" data-scroll-target="#read-this-honestly"><span class="header-section-number">11.4.1</span> ⚠️ Read this honestly</a></li>
  </ul></li>
  <li><a href="#step-5-reading-the-coefficients" id="toc-step-5-reading-the-coefficients" class="nav-link" data-scroll-target="#step-5-reading-the-coefficients"><span class="header-section-number">11.5</span> Step 5 — Reading the coefficients</a></li>
  <li><a href="#step-6-improving-it-the-skewed-target" id="toc-step-6-improving-it-the-skewed-target" class="nav-link" data-scroll-target="#step-6-improving-it-the-skewed-target"><span class="header-section-number">11.6</span> Step 6 — Improving it: the skewed target</a>
  <ul class="collapse">
  <li><a href="#seeing-the-difference" id="toc-seeing-the-difference" class="nav-link" data-scroll-target="#seeing-the-difference"><span class="header-section-number">11.6.1</span> Seeing the difference</a></li>
  </ul></li>
  <li><a href="#practice-use-case-3" id="toc-practice-use-case-3" class="nav-link" data-scroll-target="#practice-use-case-3"><span class="header-section-number">11.7</span> ✏️ Practice — use case 3</a></li>
  </ul></li>
  <li><a href="#what-the-three-use-cases-showed" id="toc-what-the-three-use-cases-showed" class="nav-link" data-scroll-target="#what-the-three-use-cases-showed"><span class="header-section-number">12</span> What the three use cases showed</a></li>
  <li><a href="#regression-20-mcqs" id="toc-regression-20-mcqs" class="nav-link" data-scroll-target="#regression-20-mcqs"><span class="header-section-number">13</span> ❓ Regression — 20 MCQs</a>
  <ul class="collapse">
  <li><a href="#the-basics" id="toc-the-basics" class="nav-link" data-scroll-target="#the-basics"><span class="header-section-number">13.0.1</span> The basics</a></li>
  <li><a href="#evaluation-metrics" id="toc-evaluation-metrics" class="nav-link" data-scroll-target="#evaluation-metrics"><span class="header-section-number">13.0.2</span> Evaluation metrics</a></li>
  <li><a href="#reading-and-improving-the-model" id="toc-reading-and-improving-the-model" class="nav-link" data-scroll-target="#reading-and-improving-the-model"><span class="header-section-number">13.0.3</span> Reading and improving the model</a></li>
  </ul></li>
  <li><a href="#regression-tasks" id="toc-regression-tasks" class="nav-link" data-scroll-target="#regression-tasks"><span class="header-section-number">14</span> 🎯 Regression — Tasks</a>
  <ul class="collapse">
  <li><a href="#warm-up" id="toc-warm-up" class="nav-link" data-scroll-target="#warm-up"><span class="header-section-number">14.1</span> Warm-up</a></li>
  <li><a href="#applying" id="toc-applying" class="nav-link" data-scroll-target="#applying"><span class="header-section-number">14.2</span> Applying</a></li>
  <li><a href="#whole-projects" id="toc-whole-projects" class="nav-link" data-scroll-target="#whole-projects"><span class="header-section-number">14.3</span> Whole projects</a></li>
  </ul></li>
  <li><a href="#before-you-move-on" id="toc-before-you-move-on" class="nav-link" data-scroll-target="#before-you-move-on"><span class="header-section-number">15</span> ✅ Before you move on</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../demos/session-01-python-refresher.html">Workshop</a></li><li class="breadcrumb-item"><a href="../demos/session-05-regression.html"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Session 5 — Regression</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Session 5 — Regression</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><strong>Supervised learning · Linear Regression · Evaluation metrics · Three complete use cases</strong></p>
<blockquote class="blockquote">
<p><strong>Sessions 1–4 got you ready. This is where you train your first model.</strong></p>
<p>Regression predicts a <strong>number</strong>. By the end you will have built three of them, and — more importantly — <strong>you will know what every evaluation metric actually means.</strong></p>
</blockquote>
<hr>
<section id="learning-outcomes" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="learning-outcomes"><span class="header-section-number">7.1</span> 🎯 Learning outcomes</h2>
<p>By the end of this session you can:</p>
<ol type="1">
<li>Tell a regression problem from a classification one, from the target column alone</li>
<li>Run the full workflow: load, explore, clean, split, train, predict, evaluate</li>
<li><strong>Explain MAE, MSE, RMSE and R² properly — including what each one hides</strong></li>
<li>Read a linear model’s coefficients out loud as a plain-English sentence</li>
<li>Judge whether a model is good enough by comparing RMSE against the target’s scale</li>
<li>Recognise when the limit is the data rather than the model</li>
</ol>
<hr>
</section>
<section id="how-this-session-is-organised" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="how-this-session-is-organised"><span class="header-section-number">7.2</span> How this session is organised</h2>
<p><strong>Three complete use cases</strong>, each chosen to show something the previous one could not.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Dataset</th>
<th>Features</th>
<th>What it teaches</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Use case 1</strong></td>
<td><code>salary_data.csv</code></td>
<td><strong>1</strong> — years of experience</td>
<td>The whole workflow, and <strong>what every metric means</strong></td>
</tr>
<tr class="even">
<td><strong>Use case 2</strong></td>
<td><code>advertising.csv</code></td>
<td><strong>3</strong> — TV, radio, newspaper</td>
<td>Reading coefficients, and dropping a useless feature</td>
</tr>
<tr class="odd">
<td><strong>Use case 3</strong></td>
<td><code>cardekho_dataset.csv</code></td>
<td><strong>10</strong> — a real used-car market</td>
<td>Encoding, scaling, and <strong>what to do when the model is not good enough</strong></td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th>#</th>
<th>Topic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><a href="#supervised-learning-regression-and-classification">Supervised learning: regression and classification</a></td>
</tr>
<tr class="even">
<td>2</td>
<td><a href="#use-case-1--salary-from-experience">Use case 1 — Salary from experience</a></td>
</tr>
<tr class="odd">
<td>3</td>
<td><a href="#use-case-2--advertising-spend-and-sales">Use case 2 — Advertising spend and sales</a></td>
</tr>
<tr class="even">
<td>4</td>
<td><a href="#use-case-3--used-car-prices">Use case 3 — Used car prices</a></td>
</tr>
<tr class="odd">
<td>5</td>
<td><a href="#what-the-three-use-cases-showed">What the three use cases showed</a></td>
</tr>
<tr class="even">
<td></td>
<td><a href="#-regression--20-mcqs">❓ 20 MCQs</a> · <a href="#-regression--tasks">🎯 Tasks</a></td>
</tr>
</tbody>
</table>
<p><strong>Practices sit between the use cases.</strong> The MCQs and tasks are at the end.</p>
<hr>
</section>
<section id="supervised-learning-regression-and-classification" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Supervised learning: regression and classification</h1>
<p><strong>Supervised</strong> means you have the answers. You show the model inputs <em>and</em> correct outputs, and it learns the mapping between them.</p>
<p>🧠 <strong>Analogy: past exam papers with the answer key.</strong> You study a hundred solved problems. Nobody explained the underlying theory — you inferred it from worked examples. Then you sit a new paper. <strong>The final exam is the test set.</strong></p>
<section id="the-two-kinds" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="the-two-kinds"><span class="header-section-number">8.1</span> The two kinds</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Regression</th>
<th>Classification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>The answer is</td>
<td>A <strong>number</strong></td>
<td>A <strong>category</strong></td>
</tr>
<tr class="even">
<td>Question</td>
<td><em>How much? How many?</em></td>
<td><em>Which one? Yes or no?</em></td>
</tr>
<tr class="odd">
<td>Example</td>
<td>Salary from experience</td>
<td>Loan approved or rejected</td>
</tr>
<tr class="even">
<td>A bad prediction is</td>
<td>Off by ₹4,000</td>
<td>Simply wrong</td>
</tr>
<tr class="odd">
<td>Typical metric</td>
<td>RMSE, R²</td>
<td>Accuracy, F1</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>A regression prediction can be nearly right. A classification prediction is right or wrong.</strong> That single difference is why the two families need completely different metrics — and it is why this session is split into Part A and Part B.</p>
</blockquote>
</section>
<section id="the-trap-numbers-that-are-really-categories" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="the-trap-numbers-that-are-really-categories"><span class="header-section-number">8.2</span> The trap: numbers that are really categories</h2>
<pre class="text"><code>age 30 + age 30 = 60        -&gt; meaningful  -&gt; age is a NUMBER
pincode + pincode           -&gt; nonsense    -&gt; pincode is a CATEGORY</code></pre>
<p><strong>If the arithmetic is meaningless, it is a category</strong> — however it is stored. Phone numbers, roll numbers, postcodes and any ID column all look numeric and are not.</p>
</section>
<section id="practice" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="practice"><span class="header-section-number">8.3</span> ✏️ Practice</h2>
<p><strong>Number (N) or category (C) — or neither?</strong></p>
<ol type="1">
<li>How much will this used car sell for?</li>
<li>Will this student pass the semester?</li>
<li>What natural groups exist among our customers?</li>
<li>How many minutes until the bus arrives?</li>
<li>A pincode column, stored as an integer</li>
</ol>
<details>
<summary>
Solutions
</summary>
<pre class="text"><code>1. N - regression
2. C - classification
3. Neither - unsupervised clustering; there is no answer to predict
4. N - regression
5. C - a CATEGORY. Adding two pincodes is nonsense, so the arithmetic
       test says it is not really a number.</code></pre>
</details>
<hr>
</section>
</section>
<section id="use-case-1-salary-from-experience" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Use case 1 — Salary from experience</h1>
<p><strong>One feature, one target, and no complications.</strong> That is exactly why we start here: <strong>every step is visible, and you can concentrate on what the metrics mean.</strong></p>
<p><strong>The question:</strong> given someone’s years of experience, predict their salary.</p>
<hr>
<section id="step-1-import-the-libraries-and-load-the-data" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="step-1-import-the-libraries-and-load-the-data"><span class="header-section-number">9.1</span> Step 1 — Import the libraries and load the data</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>dataset_url <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/tech4alltraining/aiml/refs/heads/main/datasets/regression/salary_data.csv"</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(dataset_url)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>df.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>   Experience    Salary
0         5.0   90000.0
1         3.0   65000.0
2        15.0  150000.0
3         7.0   60000.0
4        20.0  200000.0</code></pre>
<p><strong>Two columns.</strong> <code>Experience</code> is the <strong>feature</strong> — the information we are allowed to use. <code>Salary</code> is the <strong>target</strong> — the number we must predict.</p>
<hr>
</section>
<section id="step-2-exploratory-data-analysis" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="step-2-exploratory-data-analysis"><span class="header-section-number">9.2</span> Step 2 — Exploratory Data Analysis</h2>
<p><strong>Exactly the routine from Session 3.</strong> Look before you touch anything.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>df.head()</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>df.tail()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>df.info()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>df.describe()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output of <code>info()</code>:</strong></p>
<pre class="text"><code>RangeIndex: 375 entries, 0 to 374
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Experience  373 non-null    float64
 1   Salary      373 non-null    float64</code></pre>
<p><strong>375 rows, but only 373 non-null in each column — so there are two gaps in each.</strong></p>
<p><strong>Output of <code>describe()</code>:</strong></p>
<pre class="text"><code>       Experience         Salary
count  373.000000     373.000000
mean    10.030831  100577.345845
std      6.557007   48240.013482
min      0.000000     350.000000
25%      4.000000   55000.000000
50%      9.000000   95000.000000
75%     15.000000  140000.000000
max     25.000000  250000.000000</code></pre>
<p><strong>Experience runs 0 to 25 years; salary runs 350 to 250,000.</strong> The mean and median salary are close (100,577 against 95,000), so this column is <strong>not badly skewed</strong> — unlike the salary column you met in Session 3.</p>
<section id="correlation-does-experience-actually-relate-to-salary" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="correlation-does-experience-actually-relate-to-salary"><span class="header-section-number">9.2.1</span> Correlation — does experience actually relate to salary?</h3>
<p><strong>Before building anything, check that there is a relationship to find.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df.corr()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>            Experience    Salary
Experience    1.000000  0.930338
Salary        0.930338  1.000000</code></pre>
<p><strong>0.93 is a very strong positive correlation.</strong> As experience rises, salary rises with it, closely. <strong>This is the number that tells you a linear model is worth trying at all.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>sns.heatmap(df.corr(), annot<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>A heatmap is overkill for two columns</strong>, but on a dataset with fifteen it is the fastest way to see which pairs move together. <strong>Learn the habit here where it is easy to read.</strong></p>
<blockquote class="blockquote">
<p><strong>If the correlation had been 0.05, a straight line would have been the wrong tool</strong> — and you would have found that out in ten seconds rather than after building a model.</p>
</blockquote>
<hr>
</section>
</section>
<section id="step-3-preprocessing" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="step-3-preprocessing"><span class="header-section-number">9.3</span> Step 3 — Preprocessing</h2>
<section id="missing-values" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="missing-values"><span class="header-section-number">9.3.1</span> Missing values</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>df.isnull().<span class="bu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>Experience    2
Salary        2</code></pre>
<p><strong>Two gaps in each column.</strong> With 375 rows, dropping them costs well under 1% of the data — <strong>so dropping is the sensible choice here.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>df.dropna(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>(373, 2)</code></pre>
<blockquote class="blockquote">
<p><strong>Compare this with Session 3’s <code>pre_data.csv</code></strong>, where dropping three rows cost 25% of the dataset and imputation was the right answer. <strong>Same technique, opposite decision — and the deciding factor is how much data you have.</strong></p>
</blockquote>
</section>
<section id="duplicates" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="duplicates"><span class="header-section-number">9.3.2</span> Duplicates</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df.duplicated().<span class="bu">sum</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>219</code></pre>
<p><strong>219 duplicates out of 373 rows — that is 59% of the dataset.</strong></p>
<blockquote class="blockquote">
<p>⚠️ <strong>Do not remove these.</strong></p>
<p><strong>Look at what the columns are.</strong> <code>Experience</code> is a whole number of years from 0 to 25. <code>Salary</code> is a round figure. <strong>With only 26 possible experience values and a few dozen common salary figures, two different people having identical rows is completely ordinary.</strong></p>
<p><strong>Two people with 5 years of experience both earning 90,000 is not a data-entry error. It is two people.</strong></p>
<p>Removing them would delete 59% of a legitimate dataset — and it would systematically delete the <em>most common</em> combinations, which are exactly the ones the model most needs to learn.</p>
</blockquote>
<p><strong>This is Session 3’s lesson made concrete:</strong> <em>before dropping duplicates, ask whether two rows could legitimately be identical.</em> <strong>Here, obviously yes.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># df.drop_duplicates(inplace=True)   &lt;- deliberately NOT done</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="outliers" class="level3" data-number="9.3.3">
<h3 data-number="9.3.3" class="anchored" data-anchor-id="outliers"><span class="header-section-number">9.3.3</span> Outliers</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>plt.boxplot(df[<span class="st">'Experience'</span>])</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>plt.boxplot(df[<span class="st">'Salary'</span>])</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Neither box plot shows any dots beyond the whiskers.</strong> The IQR bounds work out at −12 to 32 years and −72,500 to 267,500 — <strong>and every value falls comfortably inside.</strong></p>
<p><strong>No outliers to handle.</strong></p>
</section>
<section id="encoding-and-scaling" class="level3" data-number="9.3.4">
<h3 data-number="9.3.4" class="anchored" data-anchor-id="encoding-and-scaling"><span class="header-section-number">9.3.4</span> Encoding and scaling</h3>
<p><strong>Neither is needed here:</strong></p>
<ul>
<li><strong>Encoding</strong> converts text to numbers. <strong>Both columns are already numeric</strong>, so there is nothing to encode.</li>
<li><strong>Scaling</strong> puts columns on a comparable range. <strong>Linear regression does not require it</strong> — and with a single feature there is nothing to compare against anyway.</li>
</ul>
<blockquote class="blockquote">
<p><strong>Recognising that a step is unnecessary is as important as knowing how to do it.</strong> A pipeline that scales a column for no reason is not more careful; it is just longer.</p>
</blockquote>
<hr>
</section>
</section>
<section id="step-4-train-test-split" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="step-4-train-test-split"><span class="header-section-number">9.4</span> Step 4 — Train-test split</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df.drop(<span class="st">'Salary'</span>, axis<span class="op">=</span><span class="dv">1</span>)      <span class="co"># features - everything except the target</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'Salary'</span>]                   <span class="co"># target</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape, X.shape, y.shape)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(X_train.shape, y_train.shape)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(X_test.shape, y_test.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>(373, 2) (373, 1) (373,)
(298, 1) (298,)
(75, 1) (75,)</code></pre>
<p><strong>Read those shapes carefully — they tell you the split worked.</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Shape</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>X</code></td>
<td><code>(373, 1)</code></td>
<td>373 rows, <strong>1 feature</strong></td>
</tr>
<tr class="even">
<td><code>y</code></td>
<td><code>(373,)</code></td>
<td>373 targets, and no second dimension</td>
</tr>
<tr class="odd">
<td><code>X_train</code></td>
<td><code>(298, 1)</code></td>
<td>80% of the rows</td>
</tr>
<tr class="even">
<td><code>X_test</code></td>
<td><code>(75, 1)</code></td>
<td>the remaining 20%</td>
</tr>
</tbody>
</table>
<p><strong>298 + 75 = 373.</strong> Nothing was lost.</p>
<blockquote class="blockquote">
<p><strong><code>X</code> is a DataFrame (two-dimensional) and <code>y</code> is a Series (one-dimensional).</strong> That is not an accident — scikit-learn expects a table of features and a single column of answers. <strong><code>df.drop('Salary', axis=1)</code> keeps <code>X</code> two-dimensional even with one feature</strong>, which is what the model needs.</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>No <code>stratify</code> here.</strong> That argument keeps class proportions balanced, and a regression target has no classes to balance. <strong>It is for classification only.</strong></p>
</blockquote>
<hr>
</section>
<section id="step-5-model-selection-and-training" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="step-5-model-selection-and-training"><span class="header-section-number">9.5</span> Step 5 — Model selection and training</h2>
<p><strong>Linear regression fits a straight line through the data.</strong></p>
<pre class="text"><code>Salary = slope × Experience + intercept</code></pre>
<p><strong>“Training” means finding the slope and intercept that make the errors smallest.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression()</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>model.fit(X_train, y_train)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Two lines.</strong> <code>LinearRegression()</code> creates the model; <code>.fit()</code> learns from the training data.</p>
<blockquote class="blockquote">
<p><strong>This is the pattern from Session 4’s Topic 19</strong> — create, train, predict, measure. <strong>Every model in scikit-learn works this way</strong>, so learning it once is enough.</p>
</blockquote>
<hr>
</section>
<section id="step-6-making-predictions" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="step-6-making-predictions"><span class="header-section-number">9.6</span> Step 6 — Making predictions</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> model.predict(X_test)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>y_pred[:<span class="dv">5</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>[174795.47,  99746.98, 140682.52,  72456.62, 147505.11]</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>y_test[:<span class="dv">5</span>]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>[180000.0, 65000.0, 125000.0, 80000.0, 140000.0]</code></pre>
<p><strong>Now compare them, row by row:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Actual</th>
<th>Predicted</th>
<th>Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>180,000</td>
<td>174,795</td>
<td><strong>−5,205</strong></td>
</tr>
<tr class="even">
<td>2</td>
<td>65,000</td>
<td>99,747</td>
<td><strong>+34,747</strong></td>
</tr>
<tr class="odd">
<td>3</td>
<td>125,000</td>
<td>140,683</td>
<td>+15,683</td>
</tr>
<tr class="even">
<td>4</td>
<td>80,000</td>
<td>72,457</td>
<td>−7,543</td>
</tr>
<tr class="odd">
<td>5</td>
<td>140,000</td>
<td>147,505</td>
<td>+7,505</td>
</tr>
</tbody>
</table>
<p><strong>Some predictions are close; one is out by nearly 35,000.</strong> <strong>The whole point of the next step is to turn this column of differences into a single number you can report.</strong></p>
<hr>
</section>
<section id="step-7-evaluation-metrics-properly" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="step-7-evaluation-metrics-properly"><span class="header-section-number">9.7</span> Step 7 — Evaluation metrics, properly</h2>
<p><strong>This is the most important section in Part A.</strong> Four metrics, and each answers a different question.</p>
<section id="the-problem-with-just-adding-up-the-errors" class="level3" data-number="9.7.1">
<h3 data-number="9.7.1" class="anchored" data-anchor-id="the-problem-with-just-adding-up-the-errors"><span class="header-section-number">9.7.1</span> The problem with just adding up the errors</h3>
<p><strong>Take four predictions with these errors:</strong></p>
<pre class="text"><code>prediction 1:  actual 10, predicted 11  -&gt;  error = 10 - 11 = -1
prediction 2:  actual 15, predicted 14  -&gt;  error = 15 - 14 = +1
prediction 3:  actual  9, predicted 11  -&gt;  error =  9 - 11 = -2
prediction 4:  actual  8, predicted  6  -&gt;  error =  8 -  6 = +2</code></pre>
<p><strong>Add them up:</strong></p>
<pre class="text"><code>-1 + 1 + -2 + 2  =  0</code></pre>
<blockquote class="blockquote">
<p><strong>Total error zero — and every single prediction was wrong.</strong></p>
<p><strong>The positive and negative errors cancelled out.</strong> This is why you can never simply sum the errors, and it is the reason all four metrics below do something to remove the sign.</p>
</blockquote>
<p><strong>There are two ways to remove a sign: take the absolute value, or square it. Those two choices give you MAE and MSE.</strong></p>
<hr>
</section>
<section id="mae-mean-absolute-error" class="level3" data-number="9.7.2">
<h3 data-number="9.7.2" class="anchored" data-anchor-id="mae-mean-absolute-error"><span class="header-section-number">9.7.2</span> MAE — Mean Absolute Error</h3>
<p><strong>Take the absolute value of each error, then average them.</strong></p>
<pre class="text"><code>|-1| + |+1| + |-2| + |+2|  =  1 + 1 + 2 + 2  =  6
MAE = 6 / 4 = 1.5</code></pre>
<p><strong>In words: on average, this model is wrong by 1.5.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_absolute_error</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>mae <span class="op">=</span> mean_absolute_error(y_test, y_pred)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Mean Absolute Error: </span><span class="sc">{</span>mae<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>Mean Absolute Error: 12094.170266826043</code></pre>
<blockquote class="blockquote">
<p><strong>Read that out loud: “the model is typically wrong by about ₹12,094”.</strong> <strong>That sentence is what a non-technical person actually needs</strong>, and MAE is the metric that gives it to you most directly.</p>
</blockquote>
<hr>
</section>
<section id="mse-mean-squared-error" class="level3" data-number="9.7.3">
<h3 data-number="9.7.3" class="anchored" data-anchor-id="mse-mean-squared-error"><span class="header-section-number">9.7.3</span> MSE — Mean Squared Error</h3>
<p><strong>Square each error, then average them.</strong></p>
<pre class="text"><code>(-1)² + (+1)² + (-2)² + (+2)²  =  1 + 1 + 4 + 4  =  10
MSE = 10 / 4 = 2.5</code></pre>
<p><strong>Squaring removes the sign too — but it does something else as well.</strong></p>
<blockquote class="blockquote">
<p><strong>Squaring punishes large errors far more than small ones.</strong> An error of 10 becomes 100; an error of 1 becomes 1. <strong>One big miss now counts a hundred times a small one.</strong></p>
<p><strong>That is sometimes exactly what you want</strong> — if being badly wrong occasionally is worse than being slightly wrong often.</p>
</blockquote>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>mse <span class="op">=</span> mean_squared_error(y_test, y_pred)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Mean Squared Error: </span><span class="sc">{</span>mse<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>Mean Squared Error: 241834883.89985102</code></pre>
<blockquote class="blockquote">
<p>⚠️ <strong>241 million?</strong> <strong>The units are rupees <em>squared</em>.</strong> Nobody can interpret that, and you should never put it in a report for a human. <strong>MSE is useful for comparing two models, not for describing one.</strong></p>
</blockquote>
<hr>
</section>
<section id="rmse-root-mean-squared-error" class="level3" data-number="9.7.4">
<h3 data-number="9.7.4" class="anchored" data-anchor-id="rmse-root-mean-squared-error"><span class="header-section-number">9.7.4</span> RMSE — Root Mean Squared Error</h3>
<p><strong>Take the square root of MSE.</strong></p>
<pre class="text"><code>RMSE = √2.5 = 1.58</code></pre>
<p><strong>This undoes the squaring, so the number lands back in your target’s units</strong> — while keeping MSE’s heavier punishment of large errors.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> root_mean_squared_error</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> root_mean_squared_error(y_test, y_pred)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Root Mean Squared Error: </span><span class="sc">{</span>rmse<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>Root Mean Squared Error: 15551.041184437</code></pre>
<blockquote class="blockquote">
<p><strong>RMSE is the metric to quote.</strong> It is in rupees, it is interpretable, and it does not hide occasional large mistakes the way MAE can.</p>
</blockquote>
</section>
<section id="mae-and-rmse-together-tell-you-something-neither-says-alone" class="level3" data-number="9.7.5">
<h3 data-number="9.7.5" class="anchored" data-anchor-id="mae-and-rmse-together-tell-you-something-neither-says-alone"><span class="header-section-number">9.7.5</span> MAE and RMSE together tell you something neither says alone</h3>
<pre class="text"><code>MAE  = 12,094
RMSE = 15,551</code></pre>
<p><strong>RMSE is always at least as large as MAE.</strong> <strong>How much larger tells you about the shape of your errors:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>RMSE ≈ MAE</strong></td>
<td>Errors are all roughly the same size</td>
</tr>
<tr class="even">
<td><strong>RMSE ≫ MAE</strong></td>
<td>A few predictions are badly wrong, and dragging RMSE up</td>
</tr>
</tbody>
</table>
<p><strong>Here RMSE is about 29% above MAE — a moderate gap.</strong> Most predictions are decent, and a handful are noticeably worse. <strong>Looking at the two together is free information most people ignore.</strong></p>
<hr>
</section>
<section id="r²-the-coefficient-of-determination" class="level3" data-number="9.7.6">
<h3 data-number="9.7.6" class="anchored" data-anchor-id="r²-the-coefficient-of-determination"><span class="header-section-number">9.7.6</span> R² — the coefficient of determination</h3>
<p><strong>The first three metrics tell you <em>how wrong</em> you are. R² tells you <em>how much better than nothing</em> you are.</strong></p>
<p>🧠 <strong>Analogy: comparing against a lazy guess.</strong> Suppose you refuse to build a model and simply predict the <em>average salary</em> for everyone. That is the worst reasonable guess. <strong>R² asks: how much of the error did the model remove, compared with that lazy guess?</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>R²</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1.0</strong></td>
<td>Perfect — every prediction exact</td>
</tr>
<tr class="even">
<td><strong>0.9</strong></td>
<td>The model explains 90% of the variation</td>
</tr>
<tr class="odd">
<td><strong>0.0</strong></td>
<td>No better than just guessing the average</td>
</tr>
<tr class="even">
<td><strong>Negative</strong></td>
<td><strong>Worse than guessing the average</strong> — yes, this is possible</td>
</tr>
</tbody>
</table>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> r2_score</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> r2_score(y_test, y_pred)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'R-squared: </span><span class="sc">{</span>r2<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>R-squared: 0.8991335611</code></pre>
<blockquote class="blockquote">
<p><strong>R² of 0.899 means the model explains about 90% of the variation in salary.</strong> For a model with a single feature, that is a genuinely good result — <strong>and it is what the 0.93 correlation at step 2 predicted.</strong></p>
</blockquote>
<blockquote class="blockquote">
<p>⚠️ <strong>R² of 1.0 on a test set is not a triumph — it is a warning.</strong> Real data has noise, so a perfect score almost always means the target leaked into your features.</p>
</blockquote>
<hr>
</section>
<section id="the-four-metrics-side-by-side" class="level3" data-number="9.7.7">
<h3 data-number="9.7.7" class="anchored" data-anchor-id="the-four-metrics-side-by-side"><span class="header-section-number">9.7.7</span> The four metrics side by side</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
<th>Units</th>
<th>Use it to</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>MAE</strong></td>
<td>12,094</td>
<td>Rupees</td>
<td>Say “typically off by about ₹12,000”</td>
</tr>
<tr class="even">
<td><strong>MSE</strong></td>
<td>241,834,884</td>
<td>Rupees <strong>squared</strong></td>
<td>Compare two models — never to describe one</td>
</tr>
<tr class="odd">
<td><strong>RMSE</strong></td>
<td>15,551</td>
<td>Rupees</td>
<td><strong>Report this one</strong></td>
</tr>
<tr class="even">
<td><strong>R²</strong></td>
<td>0.899</td>
<td>None</td>
<td>Say “explains 90% of the variation”</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Report RMSE and R² together.</strong> RMSE says how wrong you are in real units; R² says whether that is good relative to doing nothing. <strong>Neither is enough alone.</strong></p>
</blockquote>
<hr>
</section>
</section>
<section id="step-8-reading-the-model" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="step-8-reading-the-model"><span class="header-section-number">9.8</span> Step 8 — Reading the model</h2>
<p><strong>A linear model can be read out loud, and this is one of its great advantages.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>slope <span class="op">=</span> model.coef_</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>intercept <span class="op">=</span> model.intercept_</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Slope: </span><span class="sc">{</span>slope<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Y-Intercept: </span><span class="sc">{</span>intercept<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'X-Intercept: </span><span class="sc">{</span><span class="op">-</span>intercept<span class="op">/</span>slope<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>Slope: [6822.59017499]
Y-Intercept: 31521.077629
X-Intercept: [-4.62012]</code></pre>
<p><strong>The learned equation is:</strong></p>
<pre class="text"><code>Salary = 6,822.59 × Experience + 31,521.08</code></pre>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Value</th>
<th>What it means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Slope</strong></td>
<td>6,822.59</td>
<td><strong>Each extra year of experience is worth about ₹6,823</strong></td>
</tr>
<tr class="even">
<td><strong>Y-intercept</strong></td>
<td>31,521.08</td>
<td>The predicted salary at zero experience — a starting salary</td>
</tr>
<tr class="odd">
<td><strong>X-intercept</strong></td>
<td>−4.62</td>
<td>Where the line crosses zero salary</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>The x-intercept of −4.62 years is meaningless</strong>, and worth saying so. It is where the mathematics puts the line, not a fact about the world — <strong>you cannot have −4.62 years of experience.</strong> <strong>A model can be extended beyond its data; its answers there should not be trusted.</strong></p>
</blockquote>
<blockquote class="blockquote">
<p><strong>“Each extra year of experience is worth about ₹6,823, starting from around ₹31,500.”</strong> <strong>A model you can say in one sentence is a model you can defend in a meeting</strong> — and no other family in this session gives you that as easily.</p>
</blockquote>
<hr>
</section>
<section id="step-9-plotting-the-result" class="level2" data-number="9.9">
<h2 data-number="9.9" class="anchored" data-anchor-id="step-9-plotting-the-result"><span class="header-section-number">9.9</span> Step 9 — Plotting the result</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>plt.scatter(X_test, y_test, color<span class="op">=</span><span class="st">'black'</span>, label<span class="op">=</span><span class="st">'Actual data'</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>plt.plot(X_test, y_pred, color<span class="op">=</span><span class="st">'blue'</span>, linewidth<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="st">'Regression line'</span>, marker<span class="op">=</span><span class="st">'*'</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Experience'</span>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Salary'</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Linear Regression on Salary Data'</span>)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/s5-salary-regression-line.png" class="img-fluid figure-img"></p>
<figcaption>Scatter of actual salaries with the fitted regression line through them</figcaption>
</figure>
</div>
<p><strong>The line runs cleanly through the middle of the points</strong>, and the points sit fairly evenly above and below it. <strong>That is what a good linear fit looks like.</strong></p>
<p><strong>What to look for in this plot:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>If you see</th>
<th>It means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Points scattered evenly above and below the line</td>
<td><strong>A good fit</strong></td>
</tr>
<tr class="even">
<td>Points forming a curve around the line</td>
<td>A straight line is the wrong shape</td>
</tr>
<tr class="odd">
<td>The spread widening as x increases</td>
<td>Errors grow with the prediction — a real pattern worth handling</td>
</tr>
<tr class="even">
<td>A few points very far from the line</td>
<td>Outliers, or something the features do not capture</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Always plot a regression, even when the metrics look good.</strong> <strong>R² of 0.899 would look identical whether the relationship is a clean line or a curve the model is cutting through</strong> — and only the picture tells you which.</p>
</blockquote>
<section id="two-diagnostic-plots-worth-drawing-every-time" class="level3" data-number="9.9.1">
<h3 data-number="9.9.1" class="anchored" data-anchor-id="two-diagnostic-plots-worth-drawing-every-time"><span class="header-section-number">9.9.1</span> Two diagnostic plots worth drawing every time</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="fl">4.4</span>))</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted against actual - points should hug the diagonal</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>ax1.scatter(y_test, y_pred, alpha<span class="op">=</span><span class="fl">.6</span>, edgecolor<span class="op">=</span><span class="st">'k'</span>, linewidth<span class="op">=</span><span class="fl">.4</span>)</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>lims <span class="op">=</span> [y_test.<span class="bu">min</span>() <span class="op">-</span> <span class="dv">5000</span>, y_test.<span class="bu">max</span>() <span class="op">+</span> <span class="dv">5000</span>]</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>ax1.plot(lims, lims, <span class="st">'r--'</span>, label<span class="op">=</span><span class="st">'perfect prediction'</span>)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">'Actual salary'</span>)<span class="op">;</span> ax1.set_ylabel(<span class="st">'Predicted salary'</span>)</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">'Predicted vs actual'</span>)<span class="op">;</span> ax1.legend()</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Residuals - the errors, plotted against the prediction</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>residuals <span class="op">=</span> y_test <span class="op">-</span> y_pred</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>ax2.scatter(y_pred, residuals, alpha<span class="op">=</span><span class="fl">.6</span>, edgecolor<span class="op">=</span><span class="st">'k'</span>, linewidth<span class="op">=</span><span class="fl">.4</span>)</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>ax2.axhline(<span class="dv">0</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>)</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="st">'Predicted salary'</span>)<span class="op">;</span> ax2.set_ylabel(<span class="st">'Error (actual − predicted)'</span>)</span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="st">'Residuals'</span>)</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/s5-salary-diagnostics.png" class="img-fluid figure-img"></p>
<figcaption>Predicted versus actual salaries, and a residual plot</figcaption>
</figure>
</div>
<p><strong>Read them together:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Plot</th>
<th>What good looks like</th>
<th>What a problem looks like</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Predicted vs actual</strong></td>
<td>Points hugging the red diagonal</td>
<td>A curve, or points drifting off at one end</td>
</tr>
<tr class="even">
<td><strong>Residuals</strong></td>
<td>A <strong>shapeless cloud</strong> around zero</td>
<td>A curve, a funnel, or any visible pattern</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>The residual plot is the more sensitive of the two.</strong> A pattern in the residuals means the model is missing something systematic — <strong>and it will show a pattern long before R² drops enough to worry you.</strong></p>
</blockquote>
<hr>
</section>
</section>
<section id="practice-use-case-1" class="level2" data-number="9.10">
<h2 data-number="9.10" class="anchored" data-anchor-id="practice-use-case-1"><span class="header-section-number">9.10</span> ✏️ Practice — use case 1</h2>
<ol type="1">
<li>Load the salary dataset and print its shape, <code>info()</code> and <code>describe()</code>.</li>
<li>Compute the correlation between <code>Experience</code> and <code>Salary</code>. What does the value tell you?</li>
<li>Count the duplicates. <strong>Explain in one sentence why they should not be removed here.</strong></li>
<li>Split the data and print all four shapes. Confirm the train and test rows add up.</li>
<li>Train the model and print MAE, MSE, RMSE and R². <strong>Write the one sentence you would say to a manager.</strong></li>
</ol>
<details>
<summary>
Solutions
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np, pandas <span class="im">as</span> pd</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_absolute_error, mean_squared_error, r2_score</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>dataset_url <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/tech4alltraining/aiml/refs/heads/main/datasets/regression/salary_data.csv"</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(dataset_url)</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape)                       <span class="co"># 1  (375, 2)</span></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>df.info()</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.describe())</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.corr())                      <span class="co"># 2  0.930 - very strong positive</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a><span class="co"># As experience rises, salary rises closely with it. A straight line is</span></span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a><span class="co"># worth trying. Had this been 0.05, it would not have been.</span></span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-17"><a href="#cb46-17" aria-hidden="true" tabindex="-1"></a>df.dropna(inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb46-18"><a href="#cb46-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"duplicates:"</span>, df.duplicated().<span class="bu">sum</span>())                            <span class="co"># 3</span></span>
<span id="cb46-19"><a href="#cb46-19" aria-hidden="true" tabindex="-1"></a><span class="co"># 219 of 373 - about 59%. Experience is a whole number of years and</span></span>
<span id="cb46-20"><a href="#cb46-20" aria-hidden="true" tabindex="-1"></a><span class="co"># salary is a round figure, so two different people having identical</span></span>
<span id="cb46-21"><a href="#cb46-21" aria-hidden="true" tabindex="-1"></a><span class="co"># rows is completely ordinary. They are real people, not data errors.</span></span>
<span id="cb46-22"><a href="#cb46-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-23"><a href="#cb46-23" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df.drop(<span class="st">'Salary'</span>, axis<span class="op">=</span><span class="dv">1</span>)<span class="op">;</span> y <span class="op">=</span> df[<span class="st">'Salary'</span>]                        <span class="co"># 4</span></span>
<span id="cb46-24"><a href="#cb46-24" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb46-25"><a href="#cb46-25" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb46-26"><a href="#cb46-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(X_train.shape, X_test.shape, y_train.shape, y_test.shape)</span>
<span id="cb46-27"><a href="#cb46-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"rows add up:"</span>, <span class="bu">len</span>(X_train) <span class="op">+</span> <span class="bu">len</span>(X_test) <span class="op">==</span> <span class="bu">len</span>(X))</span>
<span id="cb46-28"><a href="#cb46-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-29"><a href="#cb46-29" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression().fit(X_train, y_train)                       <span class="co"># 5</span></span>
<span id="cb46-30"><a href="#cb46-30" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> model.predict(X_test)</span>
<span id="cb46-31"><a href="#cb46-31" aria-hidden="true" tabindex="-1"></a>mse <span class="op">=</span> mean_squared_error(y_test, y_pred)</span>
<span id="cb46-32"><a href="#cb46-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MAE  </span><span class="sc">{</span>mean_absolute_error(y_test, y_pred)<span class="sc">:,.0f}</span><span class="ss">"</span>)</span>
<span id="cb46-33"><a href="#cb46-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MSE  </span><span class="sc">{</span>mse<span class="sc">:,.0f}</span><span class="ss">"</span>)</span>
<span id="cb46-34"><a href="#cb46-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE </span><span class="sc">{</span>np<span class="sc">.</span>sqrt(mse)<span class="sc">:,.0f}</span><span class="ss">"</span>)</span>
<span id="cb46-35"><a href="#cb46-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R2   </span><span class="sc">{</span>r2_score(y_test, y_pred)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb46-36"><a href="#cb46-36" aria-hidden="true" tabindex="-1"></a><span class="co"># "The model predicts salary to within about 15,500 rupees typically,</span></span>
<span id="cb46-37"><a href="#cb46-37" aria-hidden="true" tabindex="-1"></a><span class="co">#  and explains roughly 90% of the variation in pay."</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<hr>
</section>
</section>
<section id="use-case-2-advertising-spend-and-sales" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Use case 2 — Advertising spend and sales</h1>
<p><strong>One feature was enough to learn the mechanics. Real problems have several</strong> — and that changes what you can read out of the model.</p>
<p><strong>The question:</strong> given what was spent on TV, radio and newspaper advertising, predict the resulting sales.</p>
<hr>
<section id="steps-12-load-and-explore" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="steps-12-load-and-explore"><span class="header-section-number">10.1</span> Steps 1–2 — Load and explore</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>dataset_url <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/tech4alltraining/aiml/refs/heads/main/datasets/regression/advertising.csv"</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(dataset_url)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>df.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>(200, 4)

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0</code></pre>
<p><strong>Three features and one target.</strong> Each row is one advertising campaign: what was spent on each channel, and what sales followed.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"missing:"</span>, df.isnull().<span class="bu">sum</span>().<span class="bu">sum</span>())</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"duplicates:"</span>, df.duplicated().<span class="bu">sum</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>missing: 0
duplicates: 0</code></pre>
<p><strong>Nothing to clean.</strong> That is unusual for real data, and it lets us concentrate on the modelling.</p>
<section id="correlation-now-genuinely-useful" class="level3" data-number="10.1.1">
<h3 data-number="10.1.1" class="anchored" data-anchor-id="correlation-now-genuinely-useful"><span class="header-section-number">10.1.1</span> Correlation — now genuinely useful</h3>
<p><strong>With one feature, correlation told you whether to bother. With three, it starts ranking them.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>df.corr()[<span class="st">'Sales'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>Sales        1.0000
TV           0.9012
Radio        0.3496
Newspaper    0.1580</code></pre>
<p><strong>Read that ranking:</strong></p>
<ul>
<li><strong>TV at 0.90</strong> — a very strong relationship with sales</li>
<li><strong>Radio at 0.35</strong> — moderate</li>
<li><strong>Newspaper at 0.16</strong> — weak, close to nothing</li>
</ul>
<blockquote class="blockquote">
<p><strong>This is a prediction about what the model will find</strong>, and it is worth writing down <em>before</em> you train, so you can check whether the model agrees.</p>
</blockquote>
</section>
<section id="seeing-the-three-relationships" class="level3" data-number="10.1.2">
<h3 data-number="10.1.2" class="anchored" data-anchor-id="seeing-the-three-relationships"><span class="header-section-number">10.1.2</span> Seeing the three relationships</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">13</span>, <span class="dv">4</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, channel <span class="kw">in</span> <span class="bu">zip</span>(axes, [<span class="st">'TV'</span>, <span class="st">'Radio'</span>, <span class="st">'Newspaper'</span>]):</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>    ax.scatter(df[channel], df[<span class="st">'Sales'</span>], alpha<span class="op">=</span><span class="fl">.6</span>, edgecolor<span class="op">=</span><span class="st">'k'</span>, linewidth<span class="op">=</span><span class="fl">.3</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"</span><span class="sc">{</span>channel<span class="sc">}</span><span class="ss">   (r = </span><span class="sc">{</span>df[channel]<span class="sc">.</span>corr(df[<span class="st">'Sales'</span>])<span class="sc">:.3f}</span><span class="ss">)"</span>)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="ss">f'</span><span class="sc">{</span>channel<span class="sc">}</span><span class="ss"> spend'</span>)</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Sales'</span>)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/s5-advertising-channels.png" class="img-fluid figure-img"></p>
<figcaption>Three scatter plots: TV, Radio and Newspaper spend against Sales</figcaption>
</figure>
</div>
<p><strong>The three panels show something the correlation numbers cannot:</strong></p>
<ul>
<li><strong>TV</strong> — a clear upward band, but it <strong>fans out</strong> at higher spend. High TV budgets give less predictable returns.</li>
<li><strong>Radio</strong> — a looser upward trend, more scattered throughout.</li>
<li><strong>Newspaper</strong> — close to a shapeless cloud, which is what a correlation of 0.16 looks like.</li>
</ul>
<blockquote class="blockquote">
<p><strong>That fan shape in the TV panel is exactly why you plot.</strong> No single correlation number contains it, and it would change how you advise a marketing team.</p>
</blockquote>
<hr>
</section>
</section>
<section id="steps-35-split-train-predict" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="steps-35-split-train-predict"><span class="header-section-number">10.2</span> Steps 3–5 — Split, train, predict</h2>
<p><strong>No preprocessing is needed, so we go straight to the split.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df.drop(<span class="st">'Sales'</span>, axis<span class="op">=</span><span class="dv">1</span>)     <span class="co"># all three channels</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'Sales'</span>]</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(X_train.shape, X_test.shape)</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression()</span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>model.fit(X_train, y_train)</span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> model.predict(X_test)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>(160, 3) (40, 3)</code></pre>
<p><strong>Notice <code>X_train</code> is now <code>(160, 3)</code> rather than <code>(298, 1)</code>.</strong> <strong>Three columns instead of one — and not a single line of the modelling code had to change.</strong></p>
<hr>
</section>
<section id="step-6-evaluate" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="step-6-evaluate"><span class="header-section-number">10.3</span> Step 6 — Evaluate</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>mae <span class="op">=</span> mean_absolute_error(y_test, y_pred)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>mse <span class="op">=</span> mean_squared_error(y_test, y_pred)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> np.sqrt(mse)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> r2_score(y_test, y_pred)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MAE  </span><span class="sc">{</span>mae<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MSE  </span><span class="sc">{</span>mse<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE </span><span class="sc">{</span>rmse<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R2   </span><span class="sc">{</span>r2<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>MAE  1.2748
MSE  2.9078
RMSE 1.7052
R2   0.9059</code></pre>
<p><strong>Sales are measured in thousands of units, so RMSE 1.71 means: typically off by about 1,710 units.</strong></p>
<blockquote class="blockquote">
<p><strong>R² of 0.906 with three features, against 0.899 with one in use case 1.</strong> <strong>Different datasets, so the two are not directly comparable</strong> — but both are strong fits.</p>
</blockquote>
<hr>
</section>
<section id="step-7-reading-three-coefficients" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="step-7-reading-three-coefficients"><span class="header-section-number">10.4</span> Step 7 — Reading three coefficients</h2>
<p><strong>This is what use case 1 could not show you.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, coef <span class="kw">in</span> <span class="bu">zip</span>(X.columns, model.coef_):</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:&lt;12}{</span>coef<span class="sc">:+.6f}</span><span class="ss">"</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'intercept'</span><span class="sc">:&lt;12}{</span>model<span class="sc">.</span>intercept_<span class="sc">:+.6f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>TV          +0.054509
Radio       +0.100945
Newspaper   +0.004337
intercept   +4.714126</code></pre>
<p><strong>The learned equation is:</strong></p>
<pre class="text"><code>Sales = 0.0545 × TV + 0.1009 × Radio + 0.0043 × Newspaper + 4.71</code></pre>
<p><strong>Each coefficient says: how much does Sales change when this channel goes up by one unit, holding the others fixed?</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Channel</th>
<th>Coefficient</th>
<th>Read as</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Radio</strong></td>
<td>+0.1009</td>
<td><strong>The strongest per unit spent</strong></td>
</tr>
<tr class="even">
<td><strong>TV</strong></td>
<td>+0.0545</td>
<td>About half radio’s effect per unit</td>
</tr>
<tr class="odd">
<td><strong>Newspaper</strong></td>
<td>+0.0043</td>
<td><strong>Essentially nothing</strong></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Radio is worth roughly twice TV per unit of spend.</strong> <strong>That is a budget recommendation, not just a number</strong> — and it is the kind of statement only a linear model hands you directly.</p>
</blockquote>
<section id="the-correlation-and-the-coefficient-disagree-and-both-are-right" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="the-correlation-and-the-coefficient-disagree-and-both-are-right"><span class="header-section-number">10.4.1</span> ⚠️ The correlation and the coefficient disagree — and both are right</h3>
<p><strong>Look back at the correlations:</strong></p>
<pre class="text"><code>correlation:   TV 0.90   &gt;   Radio 0.35   &gt;   Newspaper 0.16
coefficient:   Radio 0.10 &gt;   TV 0.05     &gt;   Newspaper 0.004</code></pre>
<p><strong>TV has the higher correlation, but radio has the higher coefficient. How?</strong></p>
<blockquote class="blockquote">
<p><strong>They answer different questions.</strong></p>
<p><strong>Correlation</strong> asks: <em>as TV spend rises, does Sales rise?</em> TV budgets are large, so TV spend explains a lot of the total variation — hence 0.90.</p>
<p><strong>The coefficient</strong> asks: <em>if I spend one more unit on TV, what happens?</em> <strong>Per unit spent, radio moves sales harder.</strong></p>
<p><strong>Both are true.</strong> TV explains more of what happened; radio gives more per rupee. <strong>The first is a description of the past; the second is advice about the next rupee.</strong></p>
</blockquote>
<blockquote class="blockquote">
<p>⚠️ <strong>Coefficients are only comparable like this when the features are on similar scales.</strong> Here all three are spend in the same units, so the comparison is fair. <strong>If one were in rupees and another in lakhs, you would have to scale first</strong> — use case 3 shows exactly that.</p>
</blockquote>
<hr>
</section>
</section>
<section id="step-8-should-we-drop-newspaper" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="step-8-should-we-drop-newspaper"><span class="header-section-number">10.5</span> Step 8 — Should we drop Newspaper?</h2>
<p><strong>Its coefficient is 0.004 and its correlation is 0.16. It looks useless. Test it rather than assuming.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>X2 <span class="op">=</span> df[[<span class="st">'TV'</span>, <span class="st">'Radio'</span>]]                  <span class="co"># drop Newspaper</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>X2_train, X2_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>    X2, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>model2 <span class="op">=</span> LinearRegression().fit(X2_train, y_train)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>y_pred2 <span class="op">=</span> model2.predict(X2_test)</span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"with Newspaper   : R2 </span><span class="sc">{</span>r2_score(y_test, y_pred)<span class="sc">:.4f}</span><span class="ss">  RMSE </span><span class="sc">{</span>rmse<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"without Newspaper: R2 </span><span class="sc">{</span>r2_score(y_test, y_pred2)<span class="sc">:.4f}</span><span class="ss">  "</span></span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"RMSE </span><span class="sc">{</span>np<span class="sc">.</span>sqrt(mean_squared_error(y_test, y_pred2))<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>with Newspaper   : R2 0.9059  RMSE 1.7052
without Newspaper: R2 0.9079  RMSE 1.6872</code></pre>
<blockquote class="blockquote">
<p><strong>Removing a feature made the model slightly <em>better</em>.</strong></p>
<p><strong>That surprises people, because more information ought to help.</strong> But a feature carrying almost no signal still carries noise, and the model spends a little of its capacity fitting that noise. <strong>Drop it and the model has one less distraction.</strong></p>
</blockquote>
<p><strong>And a simpler model is better for reasons beyond the score:</strong> fewer columns to collect, fewer to explain, fewer things to go wrong in production.</p>
<blockquote class="blockquote">
<p><strong>The gain here is small — 0.002 of R².</strong> <strong>Session 8 teaches you how to tell whether a difference that small is real</strong> or just the particular rows that landed in the test set. <strong>For now, note that the honest claim is “no worse, and simpler”, not “better”.</strong></p>
</blockquote>
<hr>
</section>
<section id="practice-use-case-2" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="practice-use-case-2"><span class="header-section-number">10.6</span> ✏️ Practice — use case 2</h2>
<ol type="1">
<li>Load the advertising data and print the correlation of each channel with <code>Sales</code>.</li>
<li>Train the model and print all four metrics.</li>
<li>Print the three coefficients. <strong>Which channel gives most per unit spent?</strong></li>
<li>Explain in two sentences why TV has the highest correlation but radio the highest coefficient.</li>
<li>Drop <code>Newspaper</code>, retrain, and compare. <strong>Would you ship the simpler model? Say why.</strong></li>
</ol>
<details>
<summary>
Solutions
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np, pandas <span class="im">as</span> pd</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_absolute_error, mean_squared_error, r2_score</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>dataset_url <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/tech4alltraining/aiml/refs/heads/main/datasets/regression/advertising.csv"</span></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(dataset_url)</span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.corr()[<span class="st">'Sales'</span>].sort_values(ascending<span class="op">=</span><span class="va">False</span>))                 <span class="co"># 1</span></span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df.drop(<span class="st">'Sales'</span>, axis<span class="op">=</span><span class="dv">1</span>)<span class="op">;</span> y <span class="op">=</span> df[<span class="st">'Sales'</span>]                          <span class="co"># 2</span></span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression().fit(X_train, y_train)</span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> model.predict(X_test)</span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a>mse <span class="op">=</span> mean_squared_error(y_test, y_pred)</span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MAE </span><span class="sc">{</span>mean_absolute_error(y_test,y_pred)<span class="sc">:.4f}</span><span class="ss">  MSE </span><span class="sc">{</span>mse<span class="sc">:.4f}</span><span class="ss">  "</span></span>
<span id="cb64-18"><a href="#cb64-18" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"RMSE </span><span class="sc">{</span>np<span class="sc">.</span>sqrt(mse)<span class="sc">:.4f}</span><span class="ss">  R2 </span><span class="sc">{</span>r2_score(y_test,y_pred)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb64-19"><a href="#cb64-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-20"><a href="#cb64-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n, c <span class="kw">in</span> <span class="bu">zip</span>(X.columns, model.coef_):                               <span class="co"># 3</span></span>
<span id="cb64-21"><a href="#cb64-21" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>n<span class="sc">:&lt;12}{</span>c<span class="sc">:+.6f}</span><span class="ss">"</span>)</span>
<span id="cb64-22"><a href="#cb64-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Radio, at +0.1009 per unit - roughly twice TV's +0.0545.</span></span>
<span id="cb64-23"><a href="#cb64-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-24"><a href="#cb64-24" aria-hidden="true" tabindex="-1"></a><span class="co"># 4 - Correlation asks "as TV spend rises, does Sales rise?" TV budgets</span></span>
<span id="cb64-25"><a href="#cb64-25" aria-hidden="true" tabindex="-1"></a><span class="co">#     are large, so TV explains much of the total variation.</span></span>
<span id="cb64-26"><a href="#cb64-26" aria-hidden="true" tabindex="-1"></a><span class="co">#     The coefficient asks "what does ONE MORE unit of TV buy?" - and per</span></span>
<span id="cb64-27"><a href="#cb64-27" aria-hidden="true" tabindex="-1"></a><span class="co">#     unit, radio moves sales harder. Both are true; one describes the</span></span>
<span id="cb64-28"><a href="#cb64-28" aria-hidden="true" tabindex="-1"></a><span class="co">#     past, the other advises the next rupee.</span></span>
<span id="cb64-29"><a href="#cb64-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-30"><a href="#cb64-30" aria-hidden="true" tabindex="-1"></a>X2 <span class="op">=</span> df[[<span class="st">'TV'</span>, <span class="st">'Radio'</span>]]                                               <span class="co"># 5</span></span>
<span id="cb64-31"><a href="#cb64-31" aria-hidden="true" tabindex="-1"></a>a, b, c_, d_ <span class="op">=</span> train_test_split(X2, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb64-32"><a href="#cb64-32" aria-hidden="true" tabindex="-1"></a>p2 <span class="op">=</span> LinearRegression().fit(a, c_).predict(b)</span>
<span id="cb64-33"><a href="#cb64-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"with    R2 </span><span class="sc">{</span>r2_score(y_test, y_pred)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb64-34"><a href="#cb64-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"without R2 </span><span class="sc">{</span>r2_score(d_, p2)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb64-35"><a href="#cb64-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Yes - it is no worse, and it is simpler: one fewer column to collect,</span></span>
<span id="cb64-36"><a href="#cb64-36" aria-hidden="true" tabindex="-1"></a><span class="co"># explain and maintain. The honest claim is "no worse and simpler",</span></span>
<span id="cb64-37"><a href="#cb64-37" aria-hidden="true" tabindex="-1"></a><span class="co"># not "better" - the 0.002 gain is too small to call on one split.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<hr>
</section>
</section>
<section id="use-case-3-used-car-prices" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> Use case 3 — Used car prices</h1>
<p><strong>The first two datasets were clean and cooperative. This one is neither</strong> — and it is much more like what you will actually be handed.</p>
<p><strong>The question:</strong> given a used car’s age, mileage, engine and other details, predict its selling price.</p>
<p><strong>What is different here:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Use cases 1 &amp; 2</th>
<th>Use case 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rows</td>
<td>200–375</td>
<td><strong>15,411</strong></td>
</tr>
<tr class="even">
<td>Text columns</td>
<td>None</td>
<td><strong>Six</strong></td>
</tr>
<tr class="odd">
<td>Target</td>
<td>Well behaved</td>
<td><strong>Heavily skewed</strong></td>
</tr>
<tr class="even">
<td>Result</td>
<td>Good fit</td>
<td><strong>Not good enough — and we deal with that honestly</strong></td>
</tr>
</tbody>
</table>
<hr>
<section id="step-1-load-and-explore" class="level2" data-number="11.1">
<h2 data-number="11.1" class="anchored" data-anchor-id="step-1-load-and-explore"><span class="header-section-number">11.1</span> Step 1 — Load and explore</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>dataset_url <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/tech4alltraining/aiml/refs/heads/main/datasets/regression/cardekho_dataset.csv"</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(dataset_url)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape)</span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.columns.tolist())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>(15411, 14)
['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
 'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
 'max_power', 'seats', 'selling_price']</code></pre>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"missing:"</span>, df.isnull().<span class="bu">sum</span>().<span class="bu">sum</span>())</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"duplicates:"</span>, df.duplicated().<span class="bu">sum</span>())</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'selling_price'</span>].describe())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>missing: 0
duplicates: 0

mean     7.749713e+05
50%      5.560000e+05
max      3.950000e+07</code></pre>
<blockquote class="blockquote">
<p><strong>Mean 774,971 against a median of 556,000, and a maximum of 39.5 million.</strong> <strong>The target is heavily right-skewed</strong> — most cars are ordinary and a few are extremely expensive. <strong>Remember this; it comes back at step 6.</strong></p>
</blockquote>
<section id="looking-at-the-text-columns" class="level3" data-number="11.1.1">
<h3 data-number="11.1.1" class="anchored" data-anchor-id="looking-at-the-text-columns"><span class="header-section-number">11.1.1</span> Looking at the text columns</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> df.select_dtypes(<span class="st">'object'</span>).columns:</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>col<span class="sc">:&lt;22}{</span>df[col]<span class="sc">.</span>nunique()<span class="sc">:&gt;5}</span><span class="ss"> distinct"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>car_name                121 distinct
brand                    32 distinct
model                   120 distinct
seller_type               3 distinct
fuel_type                 5 distinct
transmission_type         2 distinct</code></pre>
<p><strong>Six text columns, and they are not all the same kind of problem.</strong></p>
<hr>
</section>
</section>
<section id="step-2-preprocessing" class="level2" data-number="11.2">
<h2 data-number="11.2" class="anchored" data-anchor-id="step-2-preprocessing"><span class="header-section-number">11.2</span> Step 2 — Preprocessing</h2>
<section id="dropping-columns-that-cannot-help" class="level3" data-number="11.2.1">
<h3 data-number="11.2.1" class="anchored" data-anchor-id="dropping-columns-that-cannot-help"><span class="header-section-number">11.2.1</span> Dropping columns that cannot help</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop(columns<span class="op">=</span>[<span class="st">'Unnamed: 0'</span>, <span class="st">'car_name'</span>, <span class="st">'model'</span>])</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>(15411, 11)</code></pre>
<p><strong>Three columns removed, each for a different reason:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Column</th>
<th>Why it goes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Unnamed: 0</code></td>
<td><strong>A row number</strong> left over from how the file was saved. It is an index, not information</td>
</tr>
<tr class="even">
<td><code>car_name</code></td>
<td><strong>121 distinct values.</strong> Dummy-encoding it would add 120 columns</td>
</tr>
<tr class="odd">
<td><code>model</code></td>
<td><strong>120 distinct values</strong>, and it largely repeats <code>car_name</code></td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong><code>brand</code> is kept at 32 categories.</strong> That is still a lot, but it is genuine information — a Maruti and a BMW are different markets. <strong>The line between “a useful category” and “too many to encode” is a judgement, and 121 is clearly over it.</strong></p>
</blockquote>
</section>
<section id="encoding" class="level3" data-number="11.2.2">
<h3 data-number="11.2.2" class="anchored" data-anchor-id="encoding"><span class="header-section-number">11.2.2</span> Encoding</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> LabelEncoder</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> [<span class="st">'brand'</span>, <span class="st">'seller_type'</span>, <span class="st">'fuel_type'</span>, <span class="st">'transmission_type'</span>]:</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>    df[col] <span class="op">=</span> LabelEncoder().fit_transform(df[col])</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"all numeric:"</span>, df.select_dtypes(<span class="st">'object'</span>).empty)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>all numeric: True</code></pre>
<blockquote class="blockquote">
<p>⚠️ <strong>Label Encoding on <code>brand</code> implies an order that does not exist</strong> — that brand 20 is somehow more than brand 5. <strong>Session 3 warned about exactly this, and it matters more for linear regression than for a tree</strong>, because a linear model multiplies the code by a weight.</p>
<p><strong>Dummy variables would be more correct here.</strong> They would also add 31 columns. <strong>We use Label Encoding to keep this walkthrough readable, and note the cost honestly</strong> — one of the tasks at the end asks you to try it the other way and measure the difference.</p>
</blockquote>
<hr>
</section>
</section>
<section id="step-3-split-and-scale" class="level2" data-number="11.3">
<h2 data-number="11.3" class="anchored" data-anchor-id="step-3-split-and-scale"><span class="header-section-number">11.3</span> Step 3 — Split and scale</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df.drop(<span class="st">'selling_price'</span>, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'selling_price'</span>]</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler().fit(X_train)        <span class="co"># FIT on train only</span></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a>X_train_scaled <span class="op">=</span> scaler.transform(X_train)</span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>X_test_scaled <span class="op">=</span> scaler.transform(X_test)</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(X_train.shape, X_test.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>(12328, 10) (3083, 10)</code></pre>
<p><strong>Ten features, 12,328 training rows.</strong></p>
<section id="does-scaling-actually-change-anything-here" class="level3" data-number="11.3.1">
<h3 data-number="11.3.1" class="anchored" data-anchor-id="does-scaling-actually-change-anything-here"><span class="header-section-number">11.3.1</span> ⚠️ Does scaling actually change anything here?</h3>
<p><strong>Test it rather than assuming.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>model_scaled <span class="op">=</span> LinearRegression().fit(X_train_scaled, y_train)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>pred_scaled <span class="op">=</span> model_scaled.predict(X_test_scaled)</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>model_raw <span class="op">=</span> LinearRegression().fit(X_train, y_train)</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>pred_raw <span class="op">=</span> model_raw.predict(X_test)</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"with scaling   : R2 </span><span class="sc">{</span>r2_score(y_test, pred_scaled)<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"without scaling: R2 </span><span class="sc">{</span>r2_score(y_test, pred_raw)<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>with scaling   : R2 0.6639
without scaling: R2 0.6639</code></pre>
<blockquote class="blockquote">
<p><strong>Identical, to four decimal places.</strong></p>
<p><strong>Linear regression does not need scaling to fit well.</strong> It simply adjusts each coefficient to suit that column’s units.</p>
<p><strong>So why scale at all?</strong> <strong>Because it makes the coefficients comparable with one another</strong> — which is the whole point of step 5 below. <strong>Scaling changes what you can read, not how well the model fits.</strong></p>
</blockquote>
<hr>
</section>
</section>
<section id="step-4-train-and-evaluate" class="level2" data-number="11.4">
<h2 data-number="11.4" class="anchored" data-anchor-id="step-4-train-and-evaluate"><span class="header-section-number">11.4</span> Step 4 — Train and evaluate</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb79"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression().fit(X_train_scaled, y_train)</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> model.predict(X_test_scaled)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>mse <span class="op">=</span> mean_squared_error(y_test, y_pred)</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"MAE  </span><span class="sc">{</span>mean_absolute_error(y_test, y_pred)<span class="sc">:&gt;12,.0f}</span><span class="ss">"</span>)</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE </span><span class="sc">{</span>np<span class="sc">.</span>sqrt(mse)<span class="sc">:&gt;12,.0f}</span><span class="ss">"</span>)</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R2   </span><span class="sc">{</span>r2_score(y_test, y_pred)<span class="sc">:&gt;12.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>MAE       278,522
RMSE      503,024
R2         0.6639</code></pre>
<section id="read-this-honestly" class="level3" data-number="11.4.1">
<h3 data-number="11.4.1" class="anchored" data-anchor-id="read-this-honestly"><span class="header-section-number">11.4.1</span> ⚠️ Read this honestly</h3>
<p><strong>R² of 0.66 sounds acceptable. It is not.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb81"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"median car price : </span><span class="sc">{</span>y<span class="sc">.</span>median()<span class="sc">:&gt;12,.0f}</span><span class="ss">"</span>)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE             : </span><span class="sc">{</span>np<span class="sc">.</span>sqrt(mse)<span class="sc">:&gt;12,.0f}</span><span class="ss">"</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE as a share of the median price: </span><span class="sc">{</span>np<span class="sc">.</span>sqrt(mse)<span class="op">/</span>y<span class="sc">.</span>median()<span class="sc">:.0%}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>median car price :      556,000
RMSE             :      503,024
RMSE as a share of the median price: 90%</code></pre>
<blockquote class="blockquote">
<p><strong>The typical error is 90% of the typical car’s price.</strong></p>
<p><strong>A model that says “this car is worth ₹556,000, give or take ₹503,000” is useless to a buyer or a seller.</strong></p>
<p><strong>R² of 0.66 hid that completely.</strong> R² is a ratio with no units, so it cannot tell you whether the remaining error matters. <strong>Only putting RMSE next to the actual scale of the target reveals it.</strong></p>
</blockquote>
<p><strong>This is the most important lesson in Part A: always compare your error against the size of the thing you are predicting.</strong></p>
<hr>
</section>
</section>
<section id="step-5-reading-the-coefficients" class="level2" data-number="11.5">
<h2 data-number="11.5" class="anchored" data-anchor-id="step-5-reading-the-coefficients"><span class="header-section-number">11.5</span> Step 5 — Reading the coefficients</h2>
<p><strong>Now that the features are scaled, the coefficients are comparable.</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb83"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, coef <span class="kw">in</span> <span class="bu">sorted</span>(<span class="bu">zip</span>(X.columns, model.coef_), key<span class="op">=</span><span class="kw">lambda</span> t: <span class="op">-</span><span class="bu">abs</span>(t[<span class="dv">1</span>])):</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:&lt;20}{</span>coef<span class="sc">:&gt;14,.0f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>max_power                  641,806
vehicle_age               -181,644
mileage                     64,377
km_driven                  -50,734
engine                      50,421
transmission_type          -44,793
brand                       11,378
seats                        7,003
fuel_type                   -6,147
seller_type                -2,047</code></pre>
<p><strong>These tell a story that matches common sense:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Sign</th>
<th>Reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong><code>max_power</code></strong></td>
<td><strong>+641,806</strong></td>
<td><strong>By far the strongest.</strong> More powerful cars cost much more</td>
</tr>
<tr class="even">
<td><strong><code>vehicle_age</code></strong></td>
<td><strong>−181,644</strong></td>
<td><strong>Negative</strong> — older cars are worth less. Exactly as expected</td>
</tr>
<tr class="odd">
<td><code>km_driven</code></td>
<td>−50,734</td>
<td>Negative — more mileage, lower price</td>
</tr>
<tr class="even">
<td><code>brand</code></td>
<td>+11,378</td>
<td><strong>Small, and meaningless anyway</strong> — the label codes are arbitrary</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>The <code>brand</code> coefficient is a good example of why Label Encoding on an unordered category is unsatisfying.</strong> The model has fitted a straight line through arbitrary brand numbers. <strong>The number is not wrong arithmetically; it just does not mean anything.</strong></p>
</blockquote>
<hr>
</section>
<section id="step-6-improving-it-the-skewed-target" class="level2" data-number="11.6">
<h2 data-number="11.6" class="anchored" data-anchor-id="step-6-improving-it-the-skewed-target"><span class="header-section-number">11.6</span> Step 6 — Improving it: the skewed target</h2>
<p><strong>Step 1 noticed the target was heavily skewed. That is the problem worth attacking.</strong></p>
<p><strong>Linear regression assumes errors are roughly even across the range.</strong> With prices from 100,000 to 39.5 million, they are not — <strong>the model is being pulled around by a handful of very expensive cars.</strong></p>
<p><strong>A standard fix is to model the <em>logarithm</em> of the price instead.</strong> Taking logs compresses the long tail, so the expensive cars stop dominating.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb85"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>y_log <span class="op">=</span> np.log1p(y)          <span class="co"># log(1 + price), so a price of 0 is safe</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_log_train, y_log_test <span class="op">=</span> train_test_split(</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>    X, y_log, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>model_log <span class="op">=</span> LinearRegression().fit(X_train, y_log_train)</span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>pred_log <span class="op">=</span> model_log.predict(X_test)</span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R2 on the original target : 0.6639"</span>)</span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R2 on the log target      : </span><span class="sc">{</span>r2_score(y_log_test, pred_log)<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>Output:</strong></p>
<pre class="text"><code>R2 on the original target : 0.6639
R2 on the log target      : 0.8634</code></pre>
<blockquote class="blockquote">
<p><strong>R² rises from 0.66 to 0.86</strong> — a large improvement from one line of preprocessing, and <strong>more than any change of model would have given here.</strong></p>
</blockquote>
<blockquote class="blockquote">
<p>⚠️ <strong>Two honest caveats.</strong></p>
<p><strong>First, the two R² values are not directly comparable</strong> — one is measured on prices, the other on log-prices. <strong>To compare fairly you must convert the predictions back with <code>np.expm1()</code> and recompute RMSE in rupees.</strong></p>
<p><strong>Second, this did not make the model good — it made it better.</strong> The remaining error is still substantial. <strong>A real used-car model would need features this dataset does not have: condition, service history, accident record, and location.</strong></p>
</blockquote>
<section id="seeing-the-difference" class="level3" data-number="11.6.1">
<h3 data-number="11.6.1" class="anchored" data-anchor-id="seeing-the-difference"><span class="header-section-number">11.6.1</span> Seeing the difference</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb87"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="fl">4.4</span>))</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>ax1.scatter(y_test, y_pred, alpha<span class="op">=</span><span class="fl">.25</span>, s<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>ax1.plot([<span class="dv">0</span>, <span class="dv">4_000_000</span>], [<span class="dv">0</span>, <span class="dv">4_000_000</span>], <span class="st">'r--'</span>, label<span class="op">=</span><span class="st">'perfect prediction'</span>)</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>ax1.set_xlim(<span class="dv">0</span>, <span class="dv">4_000_000</span>)<span class="op">;</span> ax1.set_ylim(<span class="dv">0</span>, <span class="dv">4_000_000</span>)</span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">'Actual price'</span>)<span class="op">;</span> ax1.set_ylabel(<span class="st">'Predicted price'</span>)</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">'Original target'</span>)<span class="op">;</span> ax1.legend()</span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>ax2.scatter(y_log_test, pred_log, alpha<span class="op">=</span><span class="fl">.25</span>, s<span class="op">=</span><span class="dv">12</span>, color<span class="op">=</span><span class="st">'seagreen'</span>)</span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>ax2.set_xlabel(<span class="st">'Actual log(price)'</span>)<span class="op">;</span> ax2.set_ylabel(<span class="st">'Predicted log(price)'</span>)</span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="st">'Log-transformed target'</span>)</span>
<span id="cb87-12"><a href="#cb87-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-13"><a href="#cb87-13" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb87-14"><a href="#cb87-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/s5-car-log-transform.png" class="img-fluid figure-img"></p>
<figcaption>Predicted versus actual car prices, before and after log-transforming the target</figcaption>
</figure>
</div>
<p><strong>The left panel is what an unusable model looks like.</strong> The points form a wide, shapeless spread rather than following the diagonal — and notice the model rarely predicts anything above about 1.5 million, however expensive the car really was. <strong>It has learned to play safe near the middle.</strong></p>
<p><strong>The right panel is visibly tighter.</strong> Taking logs compressed the long tail, so the expensive cars stopped dominating and the model could spread its predictions properly.</p>
<p><strong>That last point is the honest conclusion: sometimes the limit is the data, not the model.</strong> <strong>No algorithm invents information that was never collected.</strong></p>
<hr>
</section>
</section>
<section id="practice-use-case-3" class="level2" data-number="11.7">
<h2 data-number="11.7" class="anchored" data-anchor-id="practice-use-case-3"><span class="header-section-number">11.7</span> ✏️ Practice — use case 3</h2>
<ol type="1">
<li>Load the car dataset and print the shape, the number of distinct values in each text column, and <code>describe()</code> for <code>selling_price</code>.</li>
<li>Explain why <code>car_name</code> and <code>model</code> are dropped but <code>brand</code> is kept.</li>
<li>Train the model and compute RMSE. <strong>Then express RMSE as a percentage of the median price and say what that means.</strong></li>
<li>Print the scaled coefficients in order of size. <strong>Do the signs of <code>vehicle_age</code> and <code>km_driven</code> make sense?</strong></li>
<li>Apply <code>np.log1p</code> to the target, retrain, and report the new R². <strong>Name the two caveats that stop this being a clean win.</strong></li>
</ol>
<details>
<summary>
Solutions
</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb88"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np, pandas <span class="im">as</span> pd</span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> LabelEncoder, StandardScaler</span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error, r2_score</span>
<span id="cb88-6"><a href="#cb88-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-7"><a href="#cb88-7" aria-hidden="true" tabindex="-1"></a>dataset_url <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/tech4alltraining/aiml/refs/heads/main/datasets/regression/cardekho_dataset.csv"</span></span>
<span id="cb88-8"><a href="#cb88-8" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(dataset_url)</span>
<span id="cb88-9"><a href="#cb88-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-10"><a href="#cb88-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape)                                                        <span class="co"># 1</span></span>
<span id="cb88-11"><a href="#cb88-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> df.select_dtypes(<span class="st">'object'</span>).columns:</span>
<span id="cb88-12"><a href="#cb88-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">:&lt;22}{</span>df[c]<span class="sc">.</span>nunique()<span class="sc">:&gt;5}</span><span class="ss">"</span>)</span>
<span id="cb88-13"><a href="#cb88-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df[<span class="st">'selling_price'</span>].describe())</span>
<span id="cb88-14"><a href="#cb88-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-15"><a href="#cb88-15" aria-hidden="true" tabindex="-1"></a><span class="co"># 2 - car_name has 121 distinct values and model has 120; dummy-encoding</span></span>
<span id="cb88-16"><a href="#cb88-16" aria-hidden="true" tabindex="-1"></a><span class="co">#     either would add over a hundred columns, and they largely repeat</span></span>
<span id="cb88-17"><a href="#cb88-17" aria-hidden="true" tabindex="-1"></a><span class="co">#     each other. brand has 32 - still many, but it is real information:</span></span>
<span id="cb88-18"><a href="#cb88-18" aria-hidden="true" tabindex="-1"></a><span class="co">#     a Maruti and a BMW are different markets.</span></span>
<span id="cb88-19"><a href="#cb88-19" aria-hidden="true" tabindex="-1"></a><span class="co">#     Unnamed: 0 is a leftover row number, not information at all.</span></span>
<span id="cb88-20"><a href="#cb88-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-21"><a href="#cb88-21" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.drop(columns<span class="op">=</span>[<span class="st">'Unnamed: 0'</span>, <span class="st">'car_name'</span>, <span class="st">'model'</span>])              <span class="co"># 3</span></span>
<span id="cb88-22"><a href="#cb88-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> c <span class="kw">in</span> [<span class="st">'brand'</span>, <span class="st">'seller_type'</span>, <span class="st">'fuel_type'</span>, <span class="st">'transmission_type'</span>]:</span>
<span id="cb88-23"><a href="#cb88-23" aria-hidden="true" tabindex="-1"></a>    df[c] <span class="op">=</span> LabelEncoder().fit_transform(df[c])</span>
<span id="cb88-24"><a href="#cb88-24" aria-hidden="true" tabindex="-1"></a>X, y <span class="op">=</span> df.drop(<span class="st">'selling_price'</span>, axis<span class="op">=</span><span class="dv">1</span>), df[<span class="st">'selling_price'</span>]</span>
<span id="cb88-25"><a href="#cb88-25" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(</span>
<span id="cb88-26"><a href="#cb88-26" aria-hidden="true" tabindex="-1"></a>    X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb88-27"><a href="#cb88-27" aria-hidden="true" tabindex="-1"></a>sc <span class="op">=</span> StandardScaler().fit(X_train)</span>
<span id="cb88-28"><a href="#cb88-28" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LinearRegression().fit(sc.transform(X_train), y_train)</span>
<span id="cb88-29"><a href="#cb88-29" aria-hidden="true" tabindex="-1"></a>pred <span class="op">=</span> model.predict(sc.transform(X_test))</span>
<span id="cb88-30"><a href="#cb88-30" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> np.sqrt(mean_squared_error(y_test, pred))</span>
<span id="cb88-31"><a href="#cb88-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE </span><span class="sc">{</span>rmse<span class="sc">:,.0f}</span><span class="ss">  =  </span><span class="sc">{</span>rmse <span class="op">/</span> y<span class="sc">.</span>median()<span class="sc">:.0%}</span><span class="ss"> of the median price"</span>)</span>
<span id="cb88-32"><a href="#cb88-32" aria-hidden="true" tabindex="-1"></a><span class="co"># The typical error is 90% of the typical car's price. R2 of 0.66 hid</span></span>
<span id="cb88-33"><a href="#cb88-33" aria-hidden="true" tabindex="-1"></a><span class="co"># that entirely, because R2 has no units.</span></span>
<span id="cb88-34"><a href="#cb88-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-35"><a href="#cb88-35" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n, c <span class="kw">in</span> <span class="bu">sorted</span>(<span class="bu">zip</span>(X.columns, model.coef_), key<span class="op">=</span><span class="kw">lambda</span> t: <span class="op">-</span><span class="bu">abs</span>(t[<span class="dv">1</span>])):  <span class="co"># 4</span></span>
<span id="cb88-36"><a href="#cb88-36" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>n<span class="sc">:&lt;20}{</span>c<span class="sc">:&gt;14,.0f}</span><span class="ss">"</span>)</span>
<span id="cb88-37"><a href="#cb88-37" aria-hidden="true" tabindex="-1"></a><span class="co"># vehicle_age is NEGATIVE - older cars are worth less. km_driven is</span></span>
<span id="cb88-38"><a href="#cb88-38" aria-hidden="true" tabindex="-1"></a><span class="co"># NEGATIVE - more mileage, lower price. Both match common sense, which</span></span>
<span id="cb88-39"><a href="#cb88-39" aria-hidden="true" tabindex="-1"></a><span class="co"># is a good sign the model has learned something real.</span></span>
<span id="cb88-40"><a href="#cb88-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-41"><a href="#cb88-41" aria-hidden="true" tabindex="-1"></a>y_log <span class="op">=</span> np.log1p(y)                                                    <span class="co"># 5</span></span>
<span id="cb88-42"><a href="#cb88-42" aria-hidden="true" tabindex="-1"></a>a, b, c_, d_ <span class="op">=</span> train_test_split(X, y_log, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb88-43"><a href="#cb88-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"log-target R2 </span><span class="sc">{</span>r2_score(d_, LinearRegression().fit(a, c_).predict(b))<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb88-44"><a href="#cb88-44" aria-hidden="true" tabindex="-1"></a><span class="co"># CAVEAT 1: the two R2 values are measured on different targets - one on</span></span>
<span id="cb88-45"><a href="#cb88-45" aria-hidden="true" tabindex="-1"></a><span class="co">#   prices, one on log-prices - so they are not directly comparable. To</span></span>
<span id="cb88-46"><a href="#cb88-46" aria-hidden="true" tabindex="-1"></a><span class="co">#   compare fairly, convert back with np.expm1() and recompute RMSE.</span></span>
<span id="cb88-47"><a href="#cb88-47" aria-hidden="true" tabindex="-1"></a><span class="co"># CAVEAT 2: better is not good. The remaining error is still large, and</span></span>
<span id="cb88-48"><a href="#cb88-48" aria-hidden="true" tabindex="-1"></a><span class="co">#   a real model would need condition, service history and location -</span></span>
<span id="cb88-49"><a href="#cb88-49" aria-hidden="true" tabindex="-1"></a><span class="co">#   features this dataset does not contain.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<hr>
</section>
</section>
<section id="what-the-three-use-cases-showed" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> What the three use cases showed</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Use case 1 — Salary</th>
<th>Use case 2 — Advertising</th>
<th>Use case 3 — Cars</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rows / features</td>
<td>373 / 1</td>
<td>200 / 3</td>
<td><strong>15,411 / 10</strong></td>
</tr>
<tr class="even">
<td>Missing values</td>
<td>2, dropped</td>
<td>None</td>
<td>None</td>
</tr>
<tr class="odd">
<td>Duplicates</td>
<td><strong>219, deliberately kept</strong></td>
<td>None</td>
<td>None</td>
</tr>
<tr class="even">
<td>Encoding</td>
<td>Not needed</td>
<td>Not needed</td>
<td><strong>4 columns</strong></td>
</tr>
<tr class="odd">
<td>Scaling</td>
<td>Not needed</td>
<td>Not needed</td>
<td><strong>For readable coefficients only</strong></td>
</tr>
<tr class="even">
<td>R²</td>
<td>0.899</td>
<td>0.906</td>
<td><strong>0.664</strong></td>
</tr>
<tr class="odd">
<td>RMSE in context</td>
<td>₹15,551 on ~₹95,000</td>
<td>1.7 on ~14</td>
<td><strong>₹503,024 on ~₹556,000</strong></td>
</tr>
<tr class="even">
<td>Verdict</td>
<td>Good</td>
<td>Good</td>
<td><strong>Not good enough</strong></td>
</tr>
</tbody>
</table>
<p><strong>Four things worth carrying forward:</strong></p>
<ol type="1">
<li><p><strong>The code barely changed.</strong> One feature or ten, 200 rows or 15,000 — <code>fit</code>, <code>predict</code>, and the same four metrics. <strong>The workflow is the skill; the dataset decides the judgements.</strong></p></li>
<li><p><strong>Not every duplicate is an error.</strong> Use case 1 kept 219 of them, because two people with the same experience and salary are two people.</p></li>
<li><p><strong>A metric with no units can hide a bad model.</strong> R² of 0.66 sounded acceptable until RMSE was placed next to the median price.</p></li>
<li><p><strong>Sometimes the limit is the data.</strong> Use case 3 improved a lot from a log transform and still was not good — because the columns that would explain a used car’s price were never collected.</p></li>
</ol>
<hr>
</section>
<section id="regression-20-mcqs" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> ❓ Regression — 20 MCQs</h1>
<p><strong>Answer from memory first, then check.</strong></p>
<section id="the-basics" class="level3" data-number="13.0.1">
<h3 data-number="13.0.1" class="anchored" data-anchor-id="the-basics"><span class="header-section-number">13.0.1</span> The basics</h3>
<p><strong>Q1.</strong> Regression predicts… - (a) A category (b) A number (c) A cluster (d) A probability only</p>
<p><strong>Q2.</strong> In <code>X = df.drop('Salary', axis=1)</code> and <code>y = df['Salary']</code>, what is <code>y</code>? - (a) The features (b) The target — the thing being predicted (c) The test set (d) The model</p>
<p><strong>Q3.</strong> Why is <code>stratify=y</code> not used in a regression split? - (a) It is a bug (b) A regression target has no classes to balance (c) It is only for large data (d) It is optional everywhere</p>
<p><strong>Q4.</strong> <code>X_train.shape</code> is <code>(298, 1)</code> and <code>X_test.shape</code> is <code>(75, 1)</code>. The original data had… - (a) 298 rows (b) 373 rows (c) 75 rows (d) 1 row</p>
</section>
<section id="evaluation-metrics" class="level3" data-number="13.0.2">
<h3 data-number="13.0.2" class="anchored" data-anchor-id="evaluation-metrics"><span class="header-section-number">13.0.2</span> Evaluation metrics</h3>
<p><strong>Q5.</strong> Four predictions have errors −1, +1, −2, +2. Their <strong>sum</strong> is… - (a) 6 (b) 0 (c) 1.5 (d) 10</p>
<p><strong>Q6.</strong> What does that sum tell you about the model? - (a) It is perfect (b) Nothing — positive and negative errors cancelled out (c) It is broken (d) The errors are small</p>
<p><strong>Q7.</strong> For those same errors, MAE is… - (a) 0 (b) 1.5 (c) 2.5 (d) 6</p>
<p><strong>Q8.</strong> For those same errors, MSE is… - (a) 1.5 (b) 2.5 (c) 10 (d) 0</p>
<p><strong>Q9.</strong> Why does MSE punish large errors more than MAE? - (a) It divides by n−1 (b) It squares each error before averaging (c) It ignores small errors (d) It uses absolute values</p>
<p><strong>Q10.</strong> MSE on the salary model was 241,834,884. Its units are… - (a) Rupees (b) Rupees <strong>squared</strong> (c) None (d) Percent</p>
<p><strong>Q11.</strong> Which metric should you quote to a non-technical stakeholder? - (a) MSE (b) RMSE (c) The slope (d) The intercept</p>
<p><strong>Q12.</strong> MAE is 12,094 and RMSE is 15,551. The gap tells you… - (a) A calculation error (b) A few predictions are noticeably worse than the rest (c) All errors are equal (d) Nothing</p>
<p><strong>Q13.</strong> R² of 0.0 means the model is… - (a) Perfect (b) No better than always predicting the average (c) Broken (d) Overfitted</p>
<p><strong>Q14.</strong> Can R² be negative? - (a) No, never (b) Yes — it means worse than predicting the average (c) Only for classification (d) Only with one feature</p>
<p><strong>Q15.</strong> R² of 1.0 on a test set most likely means… - (a) An excellent model (b) Data leakage or a bug (c) Too little data (d) The wrong metric</p>
</section>
<section id="reading-and-improving-the-model" class="level3" data-number="13.0.3">
<h3 data-number="13.0.3" class="anchored" data-anchor-id="reading-and-improving-the-model"><span class="header-section-number">13.0.3</span> Reading and improving the model</h3>
<p><strong>Q16.</strong> <code>Salary = 6,822 × Experience + 31,521</code>. The 6,822 means… - (a) The starting salary (b) Each extra year of experience is worth about ₹6,822 (c) The error (d) The R² score</p>
<p><strong>Q17.</strong> TV has the highest correlation with Sales but radio has the highest coefficient. This is… - (a) A contradiction (b) Two different questions: how much variation is explained, versus what one more unit buys (c) An error (d) Impossible</p>
<p><strong>Q18.</strong> Dropping <code>Newspaper</code> slightly <strong>improved</strong> R². Why can that happen? - (a) It cannot (b) A feature with almost no signal still carries noise the model fits (c) Fewer features are always better (d) The data was sorted</p>
<p><strong>Q19.</strong> RMSE is 503,024 and the median car price is 556,000. This means… - (a) A good model (b) The typical error is about 90% of a typical price — the model is not usable (c) R² must be negative (d) The units are wrong</p>
<p><strong>Q20.</strong> Scaling made no difference to the car model’s R². Why? - (a) A bug (b) Linear regression does not need scaling to fit; scaling makes coefficients comparable (c) The data was already scaled (d) R² ignores scale</p>
<details>
<summary>
Answers
</summary>
<p><strong>A1 — (b) A number.</strong> Classification predicts a category.</p>
<p><strong>A2 — (b) The target.</strong> <code>X</code> holds the features; <code>y</code> holds the answers.</p>
<p><strong>A3 — (b).</strong> <code>stratify</code> preserves class proportions, and a continuous target has no classes.</p>
<p><strong>A4 — (b) 373 rows.</strong> 298 + 75 = 373, and checking that they add up is a quick way to confirm the split worked.</p>
<p><strong>A5 — (b) 0.</strong> −1 + 1 − 2 + 2 = 0.</p>
<p><strong>A6 — (b) Nothing.</strong> <strong>Every prediction was wrong, and the total is zero.</strong> This is exactly why no metric simply sums the errors.</p>
<p><strong>A7 — (b) 1.5.</strong> (1 + 1 + 2 + 2) ÷ 4.</p>
<p><strong>A8 — (b) 2.5.</strong> (1 + 1 + 4 + 4) ÷ 4.</p>
<p><strong>A9 — (b) Squaring.</strong> An error of 10 becomes 100; an error of 1 stays 1.</p>
<p><strong>A10 — (b) Rupees squared.</strong> Which is why MSE is for comparing models, never for describing one to a person.</p>
<p><strong>A11 — (b) RMSE.</strong> It is in the target’s own units and it does not hide occasional large misses.</p>
<p><strong>A12 — (b).</strong> <strong>RMSE is always at least MAE; how much larger tells you about the shape of your errors.</strong> A 29% gap means a handful of predictions are noticeably worse.</p>
<p><strong>A13 — (b) No better than predicting the average.</strong></p>
<p><strong>A14 — (b) Yes.</strong> A model can be actively worse than the lazy guess.</p>
<p><strong>A15 — (b) Leakage or a bug.</strong> Real data has noise; perfection almost always means the answer got into the features.</p>
<p><strong>A16 — (b).</strong> <strong>A model you can say in one sentence is a model you can defend in a meeting.</strong></p>
<p><strong>A17 — (b).</strong> Correlation describes the past; the coefficient advises the next rupee. <strong>Both are true.</strong></p>
<p><strong>A18 — (b).</strong> The model spends a little capacity fitting that noise. <strong>Note the honest claim is “no worse and simpler”, not “better” — the gain was 0.002.</strong></p>
<p><strong>A19 — (b) Not usable.</strong> “Worth ₹556,000, give or take ₹503,000” helps nobody. <strong>R² of 0.66 hid this completely.</strong></p>
<strong>A20 — (b).</strong> Linear regression adjusts each coefficient to suit that column’s units. <strong>Scaling changes what you can read, not how well it fits.</strong>
</details>
<hr>
</section>
</section>
<section id="regression-tasks" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> 🎯 Regression — Tasks</h1>
<section id="warm-up" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="warm-up"><span class="header-section-number">14.1</span> Warm-up</h2>
<p><strong>Task 1 — The metric calculator.</strong> For the errors −3, +5, −1, +7, compute MAE, MSE and RMSE <strong>by hand</strong>, then check with scikit-learn. <strong>Explain why the sum of the errors is a useless summary.</strong></p>
<p><strong>Task 2 — Correlation first.</strong> For any regression dataset, print the correlation of each feature with the target <strong>before training</strong>. Write down which feature you expect to matter most, then check whether the model agreed.</p>
<p><strong>Task 3 — Read the equation.</strong> Train a single-feature model on the salary data and write the learned equation as one plain-English sentence. <strong>Then say what the x-intercept means and why it is not useful.</strong></p>
<p><strong>Task 4 — The duplicate decision.</strong> Count the duplicates in the salary data. <strong>Write a paragraph arguing both that they should and should not be removed</strong>, then state which side you take.</p>
<p><strong>Task 5 — RMSE in context.</strong> For each of the three use cases, express RMSE as a percentage of the target’s median. <strong>Rank the three models by how usable they are, and explain why R² gives a different ranking.</strong></p>
</section>
<section id="applying" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="applying"><span class="header-section-number">14.2</span> Applying</h2>
<p><strong>Task 6 — Feature by feature.</strong> On the advertising data, train three separate single-feature models (TV only, radio only, newspaper only). <strong>Report R² for each and compare with the three-feature model.</strong></p>
<p><strong>Task 7 — Coefficients need equal footing.</strong> Take the car dataset and print the coefficients with and without scaling. <strong>Explain why only one of the two sets can be compared across features.</strong></p>
<p><strong>Task 8 — Dummy variables instead.</strong> In use case 3, replace Label Encoding of <code>brand</code> with <code>pd.get_dummies</code>. <strong>Report the new R² and the new column count. Was the extra complexity worth it?</strong></p>
<p><strong>Task 9 — Predicted versus actual.</strong> For any of the three use cases, plot predicted against actual with a diagonal reference line. <strong>Describe the shape and say what it tells you that R² does not.</strong></p>
<p><strong>Task 10 — The residual plot.</strong> Plot the errors (<code>y_test - y_pred</code>) against the predicted values. <strong>A good model shows a shapeless cloud. Describe what you see and what any pattern would mean.</strong></p>
</section>
<section id="whole-projects" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="whole-projects"><span class="header-section-number">14.3</span> Whole projects</h2>
<p><strong>Task 11 — A fourth dataset.</strong> Find a regression dataset not used in this session and run all nine steps. <strong>Report all four metrics, and state whether the model is good enough to use, with a reason.</strong></p>
<p><strong>Task 12 — The reusable function.</strong> Write <code>run_regression(dataset_url, target)</code> that performs the whole pipeline and returns the four metrics plus the coefficients. <strong>Run it unchanged on all three datasets from this part.</strong></p>
<p><strong>Task 13 — Fix the car model.</strong> Try three improvements to use case 3: log-transform the target, add dummy variables for <code>brand</code>, and remove the most extreme prices. <strong>Report RMSE in rupees for each — converting back from log where needed — and say which helped most.</strong></p>
<p><strong>Task 14 — The honest report.</strong> For one dataset, write a one-page report: what you predicted, what data you used, all four metrics, the equation in plain English, and <strong>three situations where the model should not be trusted.</strong></p>
<p><strong>Task 15 — When regression is the wrong tool.</strong> Find a question that looks like regression but is not, and explain why. <em>(Hint: think about targets that are bounded, or counts that cannot be negative, or categories that happen to be numbered.)</em></p>
<hr>
</section>
</section>
<section id="before-you-move-on" class="level1" data-number="15">
<h1 data-number="15"><span class="header-section-number">15</span> ✅ Before you move on</h1>
<ul class="task-list">
<li><label><input type="checkbox">I can tell regression from classification by looking at the target column</label></li>
<li><label><input type="checkbox">I know why <code>stratify</code> is not used in a regression split</label></li>
<li><label><input type="checkbox">I can explain why the <strong>sum</strong> of the errors is a useless summary</label></li>
<li><label><input type="checkbox">I know MAE averages absolute errors and MSE averages squared ones</label></li>
<li><label><input type="checkbox">I know MSE’s units are the target <strong>squared</strong>, and never quote it to a person</label></li>
<li><label><input type="checkbox"><strong>I report RMSE, because it is in the target’s own units</strong></label></li>
<li><label><input type="checkbox">I know R² compares the model against always guessing the average</label></li>
<li><label><input type="checkbox">I know R² can be negative, and that 1.0 on a test set is a warning</label></li>
<li><label><input type="checkbox">I compare RMSE against the target’s median before calling a model good</label></li>
<li><label><input type="checkbox">I can read a coefficient out loud as a plain-English sentence</label></li>
<li><label><input type="checkbox">I know correlation and coefficient answer different questions</label></li>
<li><label><input type="checkbox">I plot predicted-vs-actual and residuals, not just the metrics</label></li>
<li><label><input type="checkbox"><strong>I know that sometimes the limit is the data, not the model</strong></label></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../demos/session-04-intro-ml-ai.html" class="pagination-link" aria-label="Session 4 — Introduction to Artificial Intelligence &amp; Machine Learning">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Session 4 — Introduction to Artificial Intelligence &amp; Machine Learning</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../demos/session-05b-classification.html" class="pagination-link" aria-label="Session 5B — Classification &amp; Deployment">
        <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Session 5B — Classification &amp; Deployment</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>